app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb

Part of [Refactor MiqRequestTask::Dumping. #14547](https://github.com/ManageIQ/manageiq/pull/14547).
@miq-bot assign @gmcculloug 
@miq-bot add_label fine/yes, euwe/no

Rename dumpObj to dump_obj for MiqRequestTask.

---

app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/event_parser_parse_new_target.yml

We need addtional tests for EventParser#parse_new_target

Event parser tests

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb

@borod108 @pkliczewski who can merge this?

fix toplevel constant warning - snapshots are not STI

---

spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/event_parser_parse_event.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/event_parser_parse_new_target.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_before_migration.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_target_new_vm.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/vm_fetch_disks.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/vm_fetch_no_disks.yml

via https://gist.github.com/glaszig/9170b1cf2186674faeead74a68606c5d
needed for https://github.com/ManageIQ/manageiq/pull/14270
cc @jrafanie

convert cassettes to webmock-2.0 compatible format

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/state_machine.rb
app/models/manageiq/providers/redhat/infra_manager/provision_via_iso/state_machine.rb
app/models/manageiq/providers/redhat/infra_manager/provision_via_pxe/state_machine.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_via_iso/state_machine_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_via_pxe/state_machine_spec.rb

Fix iso provisioning

---

app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
content/service_dialogs/transform-vm.yml
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1404920

Add support for v2v async task

---

app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
content/service_dialogs/transform-vm.yml
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1404920

Add `install drivers` option to V2V

---

app/models/manageiq/providers/redhat/infra_manager/vm_import.rb

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1404920

v2v: Add support for post-import network configuration

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/configuration/network.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_via_pxe/state_machine_spec.rb

Part of the PXE provisioning process which had to do with finding the mac address
was broken.
https://bugzilla.redhat.com/show_bug.cgi?id=1454861

Fix provisioning from PXE with the OvirtSDK

---

spec/models/manageiq/providers/redhat/infra_manager/provision/state_machine_spec.rb

Added specs for state machine when using version 4 of the api

Added specs for state machine when using version 4 of the api

---

app/models/manageiq/providers/redhat/builder.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/strategies/api3.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/strategies/api4.rb
app/models/manageiq/providers/redhat/inventory.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/collector/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
app/models/manageiq/providers/redhat/inventory/parser.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

RFE link: https://bugzilla.redhat.com/1466172

Preparation for graph refresh implementation

---

.rspec
.rspec_ci
Rakefile
bin/setup
bin/update
config/settings.yml
lib/tasks_private/spec.rake
spec/spec_helper.rb

ran the generator again with
```bash
bundle exec rails g provider <name> --path ../
```
these are the changes.

run provider generator to sync changes from core

---

app/models/manageiq/providers/redhat/inventory/collector.rb

Add the missing connection variable

Fix missing variable in disks preloading

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

The UI is moving towards validating credentials on the queue to allow for validating credentials in separate zones utilizing a `raw_connect` class method, rather than needing to create a temporary EMS for validation.
While most providers have a single `raw_connect` class method, the Ovirt provider does not. This PR essentially adds a wrapper around a couple of the other methods found within the `api_integration` module that allows for different versions of raw connect to be called by accepting a version parameter.
It also decrypts that password before passing it to the existing functions, because passwords will be encrypted now that we will be placing them on the queue. This function will also work with unencrypted passwords.
For more information, see: …

add raw_connect class method

---

content/service_dialogs/transform-vm.yml

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1467858

v2v: Rephrase ISO driver label

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/parser.rb

When we create new template we want to target this template during
a refresh.
Bug-Url:
https://bugzilla.redhat.com/1451577

Target template

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb

Handle targeted refresh of a vm without any disks.

Graph refresh

---

content/service_dialogs/transform-vm.yml

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1472843

v2v: Make "install drivers" checkbox dynamic

---

tools/generate_refresh_template_spec.rb
tools/refresher_v4_spec_generator_template.txt

This is a half automatic tool that allows to create a test for refresh based on existing working refresh.

Tool to create refresh test

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/strategies/v4.rb

Original implementation only provided such functionality for api v3.

Target new template when using api v4

---

app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb

See https://github.com/ManageIQ/manageiq-smartstate/pull/33
@agrare Please review.

File.uri_to_local_path moved to manageiq-smartstate gem

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Currently when using version 4 of the SDK is enabled the provider raises
an exception when it can't determine what versions of the API are
supported by the oVirt server. But this is a normal situation. It
happens in general when the credentials of the server are not known yet,
for example when the oVirt server has been discovered scanning a range
of IP addresses. If an exception is reaised then the discovery process
will fail. To avoid this issue this patch changes the provider so that
it tolerates this situation, and assumes that the server supports at
least version 3 of the API.
This patch addresses the following bug:
RHV41 Provider Discovery failure
https://bugzilla.redhat.com/1502963

Assume 3 when can't determine API version

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
app/models/manageiq/providers/redhat/infra_manager/provision/state_machine.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
app/models/manageiq/providers/redhat/infra_manager/vm/operations/power.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/state_machine_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb

This PR provide sysprep support by sending complete xml file so there is no need to further customize it on ovirt side.
Bug-Url:
https://bugzilla.redhat.com/1323289

Support sysprep for windows templates

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

We need to use lazy_find_by for hash index
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1506463

We need to use lazy_find_by for hash index

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host.yml

Graph and regular refreshes fails when triggered by host removed event.
This PR fixes the issue.
Bug-Url:
https://bugzilla.redhat.com/1508831

Refresh a host when removed

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/builder.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb

The remote console code is changed to support also v4.
https://bugzilla.redhat.com/show_bug.cgi?id=1512364

Fix remote console for v4

---

app/models/manageiq/providers/redhat/inventory/parser/network_manager.rb
app/models/manageiq/providers/redhat/network_manager.rb
app/models/manageiq/providers/redhat/network_manager/floating_ip.rb
app/models/manageiq/providers/redhat/network_manager/network_router.rb
app/models/manageiq/providers/redhat/network_manager/security_group.rb
config/settings.yml

oVirt network provider support routers, security groups and floating ips

oVirt network provider support routers, security groups and floating ips

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb

Depends-on: https://github.com/ManageIQ/manageiq/pull/16526

Use supports_vm_import? instead of validate_import_vm

---

manageiq-providers-ovirt.gemspec

This version of the SDK is backwards compatible with the previous one,
but it also introduces support for the features that have been added to
oVirt in version 4.2.
The more relevant change in the SDK itself is the addition of exceptions
specific for authentication failures and timeouts, which are convenient
to simplify error handling in the provider.

Update to version 4.2.0 of the oVirt Ruby SDK

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_after_publish_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/response_yamls/template_after_publish_target_hash.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_publish_vm_to_template.yml

Spec to check that after refreshing new target template vm.ems_cluster is not
nil.

Add spec for target new_refresh

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

The way to handle errors raised from credentials verification for a new
provider and an existing providers was diffrent, which caused diffrent
error messages to be displayed.
This fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1519815

Credential verification errors for new provider

---

manageiq-providers-ovirt.gemspec

We want to use the latest ovirt gem.

oVirt gem update

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Fix message for credentials validation
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1533486

Fix message for credentials validation

---

app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_targeted_template.yml

Test that when a template does not exist on the provider a targeted refresh
will disconnect it from the ems.
This depends on: https://github.com/ManageIQ/manageiq/pull/16718

Add test for disconnecting ems on targeted refresh

---

locale/es/ManageIQ_Providers_Ovirt.po
locale/fr/ManageIQ_Providers_Ovirt.po

This PR contains final translation fixes / polishing for Gaprindashvili GA

[GAPRINDASHVILI] Final translations for gaprindashvili

---

app/models/manageiq/providers/redhat/discovery.rb

https://github.com/ManageIQ/manageiq-network_discovery/issues/8
Depends upon https://github.com/ManageIQ/manageiq/pull/16916

Network discovery probe relocation

---

locale/ManageIQ_Providers_Ovirt.pot
locale/en/ManageIQ_Providers_Ovirt.po
locale/es/ManageIQ_Providers_Ovirt.po
locale/fr/ManageIQ_Providers_Ovirt.po
locale/ja/ManageIQ_Providers_Ovirt.po
locale/pt_BR/ManageIQ_Providers_Ovirt.po
locale/zh_CN/ManageIQ_Providers_Ovirt.po

Updated catalogs for next Gaprindashvili update release.

[GAPRINDASHVILI] Update gettext catalogs for Gaprindashvili update release

---

locale/es/ManageIQ_Providers_Ovirt.po
locale/fr/ManageIQ_Providers_Ovirt.po
locale/ja/ManageIQ_Providers_Ovirt.po
locale/pt_BR/ManageIQ_Providers_Ovirt.po
locale/zh_CN/ManageIQ_Providers_Ovirt.po

Up-to-date translations for next Gaprindashvili update release.

[GAPRINDASHVILI] Update translations for g update

---

app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_recording_modifier_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_huge_async_spec.rb
spec/support/modify_refresh_yml_recording.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_for_mod.yml

Added spec for scale.
Add a fix for custom saving block (suggested by Ladas)
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1566468

Performance improvements for graph refresh

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_target_template_disconnect.yml

Revert the https://github.com/ManageIQ/manageiq-providers-ovirt/pull/257
accidental merge.

Revert merge

---

config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb

Use graph refresh as the default.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1553383
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1550579

Use Graph refresh by default

---

lib/manageiq/providers/ovirt/engine.rb

See ManageIQ/manageiq-ui-classic#4496 for primary motivation.

Add plugin display name

---

app/models/manageiq/providers/redhat/inventory.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/parser.rb
app/models/manageiq/providers/redhat/inventory/persister.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_collections.rb

Ovirt manager_ref is just [:uid_ems] which differs from core

Ovirt manager_ref is just [:uid_ems] which differs from core

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

We did not pass the sparse and storage_domain parameters when
provisioning a VM using version 4 of the sdk.

Fix setting storage attributes during vm provision

---

app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb

Move ManagerRefresh to InventoryRefresh
Depends on:

Move ManagerRefresh to InventoryRefresh

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb

Provisioning with kickstart was not implemented for version 4 of the api.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1613326

Fix ISO provisioning with kickstart

---

CHANGELOG.md

[Changelog] Add Sprint 97 and Hammer Beta1 update

---

spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml

Rerecorded ovn refresh to fix the hammer branch

[HAMMER] Fix ovn recording for hammer branch

---

app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb

When searching for EmsFolders and ResourcePools by uid_ems scope by the
ems_id to prevent resources from being assigned to a folder in the wrong
EMS.
Fixes: https://github.com/ManageIQ/manageiq-providers-ovirt/issues/321

Scope EmsFolder and ResourcePool queries by ems_id

---

app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb

Manual backport of https://github.com/ManageIQ/manageiq-providers-ovirt/pull/322
When searching for EmsFolders and ResourcePools by uid_ems scope by the
ems_id to prevent resources from being assigned to a folder in the wrong
EMS.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1660097

[GAPRINDASHVILI] Scope EmsFolder and ResourcePool queries by ems_id

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml

The when refreshing a vm its relationship with the host was not properly refreshed.
This fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1627297

Fix bug in vm targeted refresh

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_template_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml

Add spec to check that target refreshing a template properly sets the
host association when the template has placement_policy defined.

Add spec for graph target template refresh

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

@agrare @jrafanie Please review.

Remove references to MiqPassword

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

Make remove disk work both through the API and the UI.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692801

Fix removing a disk from a Vm

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_after_publish_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_recording_modifier_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_template_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_huge_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

This PR only removes copy pasted code

Refresh specs refactoring, part1

---

lib/manageiq/providers/ovirt/engine.rb

Change plugin common methods to class methods

Change plugin common methods to class methods

---

content/service_dialogs/transform-vm.yml

We validate presence on this and all the rest of them in this file are set so this feels like it should be too. 
Found here: https://github.com/ManageIQ/manageiq/pull/18778#issuecomment-493368969,
thanks, sorry @himdel

Since we validate that this is not blank, it probably shouldn't be blank

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/snapshot_disks_mixin.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/support/modify_refresh_yml_recording.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_for_mod.yml

Implement collecting total_size from snapshots - we are not actually
collecting the "total_size" attribute since it actually does not make
sense for snapshots, rather, we are collecting the "actual_size"
attribute from the rhv api.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1608475

Collecting snapshots total_size

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/api4.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

History:
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/374
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/307/files
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1697467
@borod108, i can't test 'CINDER' cause i haven't it in my env :(

ISCSI duplication (reopen)

---

manageiq-providers-ovirt.gemspec

Bump ovirt-engine-sdk version

---

app/models/manageiq/providers/redhat/inventory/collector.rb

Add a method for fixing SSA snapshot disks collection.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535782

Add a method for SSA

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

RHV engine decides which changes can be applied live leaving the other
for the 'next_run'.
If a next_run configuration is already pending, the new update request
must be sent with the 'next_run' option set to true.
This is necessary to merge new specs with all the others waiting to be
merged.
resolve #416

Memory and CPU reconfigure applied at the same time

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/update_cloud_init_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Fix most of the style issues highlighted by rubocop in the PR
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/423

Cleanup most of the code style issues

---

app/models/manageiq/providers/redhat/network_manager/event_catcher.rb
app/models/manageiq/providers/redhat/network_manager/metrics_collector_worker.rb
app/models/manageiq/providers/redhat/network_manager/refresh_worker.rb

Requires https://github.com/ManageIQ/manageiq/pull/19516

Rely on the default implementation of .ems_class

---

spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Reverts ManageIQ/manageiq-providers-ovirt#438

Revert "Update specs to match behavior of change in core PR 19212 (auth user changed)"

---

spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Depends:
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/33

Update specs for storages belonging to an EMS

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/storage.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Depends:
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/35

Subclass Storages

---

CHANGELOG.md

Changelog for Sprint 126

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/datacenter.rb
app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
app/models/manageiq/providers/redhat/infra_manager/folder.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Merge together with: https://github.com/ManageIQ/manageiq/pull/19534

Subclass EmsFolders and Datacenters

---

app/models/manageiq/providers/redhat/infra_manager/scanning.rb
app/models/manageiq/providers/redhat/infra_manager/scanning/job.rb
app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb

State Machine diagram for this subclass of VmScan.

Subclass VmScan job as ManageIQ::Providers::Redhat::InfraManager::Scanning::Job

---

app/models/manageiq/providers/redhat/infra_manager/event_parser.rb

The hash isn't an ActiveRecord object yet so we can't use
f.kind_of?(Datacenter)

Don't check for Datacenter class

---

spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb

Some cleanup in yaml and specs

Code style cleanup

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

ems_ref is explicity set as location attribute for LOCALFS
storagedomains.
In the upstream master this was also the implicit value that the inventory_refresh is setting in case of location nil, but for hammer and ivanchuck this is necessary to fix the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1798795

Add location for localfs storage

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
app/models/manageiq/providers/redhat/infra_manager/vm.rb
app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb

Introduce disk resize for VMs
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1671330

Vm disk resize

---

app/models/manageiq/providers/redhat/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/106
Core PR: https://github.com/ManageIQ/manageiq/pull/20039

Make Provider Catalog Types Pluggable

---

app/models/manageiq/providers/redhat/infra_manager/vm/operations.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb

Needed for: https://github.com/ManageIQ/manageiq/pull/20222

Add supports terminate feature

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

RestClient is not used anymore in this provider and RestClient::Unauthorized
can be uninitialized

Remove RestClient

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/vm.rb
app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb

Introduce disk resize for VMs
(cherry picked from commit 19997d1)
Backport of #483
Related to BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1671330

[IVANCHUK] Vm disk resize

---

spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_lans_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_multi_datacenter_network_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_ports_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml

For each vm there will be a request to get applications.
This PR add mock requests to VCRs, returning empty applications section, as a temporary fix to specs failing

Add applications requests to VCRs

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

**Before:**
**After:**
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/issues/508
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818

Adjusted DDF schema and validation for creating new providers

---

spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml

Add applications GET request to old VCR
Related to: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/507#issuecomment-681922222

[JANSA] Fix network spec VCR

---

spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_lans_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml

Fix VCRs for applications GET requests
Cherry pick from (0c96c4a40f1a37164e9a868d7759b7b937be3b7c)
Related to https://github.com/ManageIQ/manageiq-providers-ovirt/pull/507#issuecomment-685966757

[IVANCHUK] VCR spec fixes

---

app/models/manageiq/providers/redhat/infra_manager.rb

https://github.com/ManageIQ/manageiq-ui-classic/issues/7277

Update DDF schema to version 2

---

.codeclimate.yml
.gitignore
.rubocop.yml
.rubocop_cc.yml
.travis.yml
README.md
Rakefile
bin/ci/after_script
lib/manageiq/providers/ovirt/engine.rb
lib/tasks/README.md
lib/tasks_private/spec.rake
manageiq-providers-ovirt.gemspec
spec/spec_helper.rb

Plugin Generator Updates

---

.codeclimate.yml
.rubocop.yml
.rubocop_cc.yml
manageiq-providers-ovirt.gemspec

Depends on: https://github.com/ManageIQ/miq_bot/pull/506

Switch to manageiq-style

---

lib/manageiq/providers/ovirt/engine.rb

Move logger initialization and configuration into plugins

Move logger initialization and configuration into plugins

---

app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb

https://github.com/ManageIQ/manageiq/pull/21094

Don't manually set miq_template's model_class

---

app/models/manageiq/providers/redhat/network_manager/cloud_network.rb
app/models/manageiq/providers/redhat/network_manager/cloud_network/private.rb
app/models/manageiq/providers/redhat/network_manager/cloud_network/public.rb
app/models/manageiq/providers/redhat/network_manager/cloud_subnet.rb
app/models/manageiq/providers/redhat/network_manager/floating_ip.rb
app/models/manageiq/providers/redhat/network_manager/network_port.rb
app/models/manageiq/providers/redhat/network_manager/network_router.rb
app/models/manageiq/providers/redhat/network_manager/security_group.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Fixes https://travis-ci.com/github/ManageIQ/manageiq-providers-ovirt/jobs/503285272#L2196-L2356
Depends:

Fix OVN NetworkManager subclass spec failures

---

app/models/manageiq/providers/redhat/infra_manager.rb

https://github.com/ManageIQ/manageiq/pull/21224

Add supports :metrics feature

---

app/models/manageiq/providers/redhat/infra_manager/vm/operations/power.rb

Goes with https://github.com/ManageIQ/manageiq/pull/21278

Convert Vm#validate_pause to SupportsFeatureMixin

---

systemd/manageiq-providers-redhat_infra_manager_event_catcher@.service
systemd/manageiq-providers-redhat_infra_manager_metrics_collector@.service
systemd/manageiq-providers-redhat_infra_manager_refresh@.service
systemd/manageiq-providers-redhat_network_manager_event_catcher@.service
systemd/manageiq-providers-redhat_network_manager_refresh@.service

part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)

add properties files to systemd

---

systemd/manageiq-providers-redhat_infra_manager_event_catcher@.service
systemd/manageiq-providers-redhat_infra_manager_metrics_collector@.service
systemd/manageiq-providers-redhat_infra_manager_refresh@.service
systemd/manageiq-providers-redhat_network_manager_event_catcher@.service
systemd/manageiq-providers-redhat_network_manager_refresh@.service

run services as manageiq user

---

manageiq-providers-ovirt.gemspec

Fixes https://github.com/ManageIQ/manageiq-providers-ovirt/issues/580

Bump ovirt_metrics for rails 6 fix

---

app/models/manageiq/providers/redhat/infra_manager.rb

part of ManageIQ/manageiq#21573

converting supported_for_create to supports :create

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

Fix ems_custom_fields manager_ref

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/network_manager.rb

Follow-up to: https://github.com/ManageIQ/manageiq/pull/21542
cc @kbrock

Cleanup duplicated supports_authentication? methods

---

app/models/manageiq/providers/redhat/infra_manager/host.rb

Required for:
* https://github.com/ManageIQ/manageiq/pull/21847

Convert validate* to supports? for Host operations

---

app/models/manageiq/providers/redhat/infra_manager.rb

Continuing to remove uneeded memoization.
@miq-bot add-label bug
@miq-bot add-label najdorf/yes?

Removing Memoization

---

content/miq_dialogs/miq_provision_ovirt_dialogs_clone_to_template.yaml
content/miq_dialogs/miq_provision_ovirt_dialogs_clone_to_vm.yaml
content/miq_dialogs/miq_provision_ovirt_dialogs_template.yaml

Related:
- https://github.com/ManageIQ/manageiq-content/pull/713
@miq-bot assign @agrare 

Add provisioning content dialog

---

spec/models/manageiq/providers/ovirt/infra_manager/vm_spec.rb

part of https://github.com/ManageIQ/manageiq/issues/21179

rename Vm Operation context

---

app/models/manageiq/providers/ovirt/infra_manager.rb
app/models/manageiq/providers/ovirt/infra_manager/snapshot.rb
spec/models/manageiq/providers/ovirt/infra_manager/refresher/refresher_4_async_graph_spec.rb

Subclass Snapshot under Ovirt::InfraManager

---

app/models/manageiq/providers/ovirt/connection_manager.rb
spec/models/manageiq/providers/ovirt/connection_manager_spec.rb

The ManageIQ project is copyright "ManageIQ Authors"

Remove Red Hat Copyright notice

---

app/models/manageiq/providers/ovirt/infra_manager/host.rb

A follow up on https://github.com/ManageIQ/manageiq-providers-red_hat_virtualization/pull/20#issuecomment-1463961348
Introducing credential endpoints for host.

params_for_update schema fields for Hosts

---

app/models/manageiq/providers/ovirt/network_manager/event_catcher.rb

Petrosian direct PR for https://github.com/ManageIQ/manageiq-providers-ovirt/pull/632
Same fix as https://github.com/ManageIQ/manageiq-providers-red_hat_virtualization/pull/25

[PETROSIAN] Stop Ovirt OVN Event Catcher from starting

---

spec/models/manageiq/providers/ovirt/infra_manager/event_parser_spec.rb
spec/models/manageiq/providers/ovirt/infra_manager/refresher/ovirt_refresher_spec_common.rb

Part of https://github.com/ManageIQ/manageiq/issues/22696

Use unsafe_load to load a test file with unpermitted classes

---

manageiq-providers-ovirt.gemspec

via https://github.com/ManageIQ/ovirt_metrics/pull/48

Set minimum version to support rails 7

---

app/models/manageiq/providers/ovirt/infra_manager.rb
app/models/manageiq/providers/ovirt/network_manager.rb
config/settings.yml

https://github.com/ManageIQ/manageiq/issues/19707

Move default filtered event names to Settings

---

.gitignore
config/secrets.defaults.yml
lib/manageiq/providers/ovirt/engine.rb
spec/config/secrets.defaults.yml
spec/models/manageiq/providers/ovirt/infra_manager/refresher/ovirt_refresher_spec_common.rb
spec/spec_helper.rb

Switch to use VcrSecrets helper from core

---

lib/manageiq/providers/ovirt/engine.rb

Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509

Drop to_s on engine paths

---

app/models/manageiq/providers/ovirt/network_manager.rb

Move generic _queue methods into base NetworkManager
