.rubocop_local.yml

Fixes:
```
$ rubocop -d app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb 
For /home/bdunne/projects/redhat/manageiq-providers-openstack: configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rubocop.yml
configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml
Default configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/default.yml
Inheriting configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/enabled.yml
Inheriting configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/disabled.yml
Inheriting configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rub …
```

Add rubocop allowed global variable for logger

---

app/models/manageiq/providers/redhat/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Change "Red Hat Virtualization Manager" to "Red Hat Virtualization"
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1403358
This goes with:
https://github.com/ManageIQ/manageiq-ui-classic/pull/973
https://github.com/ManageIQ/manageiq/pull/14703

Change RHVM to RHV

---

app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb

When using automation we see that there is an issue in validate_import_vm
and there is a time when api_version is not avialbale. We need to make sure
that validation passes.

Renderer fails when calling validate_import_vm

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Change method highest_allowed_api_version return value from integer to string for consistency.

Change method return value for consistency

---

app/models/manageiq/providers/redhat/infra_manager/vm/operations/snapshot.rb
spec/models/manageiq/providers/redhat/infra_manager/operations/snapshot_spec.rb

In the snapshot screen when the "active" snapshot is selected
the revert button should be disabled for RHV.
If VM is up, the 'revert' button is disabled due to VM status not 'DOWN'.
If VM is down and the active snapshot is selected, the 'revert' button
is disabled due to selection of 'active' snapshot.
http://bugzilla.redhat.com/1396068

No revert for "active" snapshot

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/event_catcher/runner.rb
lib/manageiq/providers/ovirt/legacy/event_monitor.rb
lib/manageiq/providers/ovirt/legacy/inventory.rb
manageiq-providers-ovirt.gemspec

Now that the oVirt provider has been extracted to a separate repository,
it makes sense to move all the oVirt specific code from
'manageiq-gems-pending' to this repository.
This patch moves the 'ovirt_event_monitor.rb' and 'ovirt_inventory.rb'
files. These files implement event monitoring and inventory collection,
using version 3 of the oVirt API and the 'ovirt' gem. As there is an
ongoing effort to use version 4 of the oVirt API, and the oVirt SDK,
these files have been added to a new 'ManageIQ::Providers::Ovirt::Legacy'
module, to make it explicit that this code will eventually be removed.
https://github.com/ManageIQ/manageiq-providers-ovirt/issues/8

Move code from manageiq-gems-pending

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb

There was a mistake in the signature of the partial_host_hash method in the v4 parser.

Fix partial refresh with new host

---

manageiq-providers-ovirt.gemspec

The new version of the gem fixes the following problems:
Add VM FQDN to guest_info
https://bugzilla.redhat.com/1417965
Fix handling of version 4.y in Vm.attach_payload
https://bugzilla.redhat.com/1441746

Use version 0.16.0 of the 'ovirt' gem

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1.yml

The PR allows to save the FQDN when it is reported by the VM's
guest agent.
https://bugzilla.redhat.com/show_bug.cgi?id=1417965

RHV VM not saving FQDN

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/ovirt_services.rb
app/models/manageiq/providers/redhat/infra_manager/provision/state_machine.rb
app/models/manageiq/providers/redhat/infra_manager/provision_via_iso/state_machine.rb
app/models/manageiq/providers/redhat/infra_manager/provision_via_pxe/state_machine.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_via_pxe/state_machine_spec.rb

This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1446409

Fix rescue during PXE and ISO provisioning

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb

Currently the mechanism used to support version 3 of the oVirt API uses
the Ruby `method_missing` mechanism to transform certain method calls
that are intended for the Ruby SDK into the corresponding methods of the
`ovirt` gem. But the implementation didn't take into account that some
of those methods take blocks as parameters. For example, the `start`
method of the `Vm` class takes a block that is used to customize the
request body, in particular to include the `use_cloud_init`parameter:
```ruby
def vm_start(vm, cloud_init)
vm.with_provider_object do |rhevm_vm|
rhevm_vm.start { |action| action.use_cloud_init(true) if cloud_init }
end
rescue Ovirt::VmAlreadyRunning
end
```
With the current implementation those blocks are silently ignored. That
means, for example, that virtual machines are …

Handle blocks when using `method_missing`

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
lib/manageiq/providers/ovirt/legacy/inventory.rb
manageiq-providers-ovirt.gemspec

The PR handles two issues with host targeting refresh:
1. When targeting a refresh of a single host, no vms or templates are
reported. Therefore the vm or template collected array should be handled
in case of nil.
2. In V3 the host resources retrieved by
/ovirt-engine/api/hosts/{host:id} contains the statistics element. The
statistics element contains a reference to the host element. The xpath
used to collect similar host entries considered the host sub-element
as a resource to collect, which lead to collecting the same host
multiple times. By specifying the exact top level host path, this will
be avoided.
https://bugzilla.redhat.com/show_bug.cgi?id=1448690

Fix host targeted refresh

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb

When performing host targeted refresh in v4, the networks should be
collected as well, so the vlan and network name will be updated for the
host.
http://bugzilla.redhat.com/1449092

Fix host targeted refresh in v4

---

app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb

There is no need to include `job.guid` into error message when proxy for smart state analysis not available - proxy is instance of `MiqServer` and does not depend on job instance.
This PR is follow-up for https://github.com/ManageIQ/manageiq/pull/15009
@miq-bot add-label technical debt
\cc @jrafanie

Remove Job#guid from logging proxy info.

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

Fix fetching ISO images from non active domains
We used to ignore the data-center level when looking for an ISO domain,
as a result we would sometimes take an ISO domain which was not attached to
an active data-center.
We now first find a data-center which is "up" and then take an ISO domain which is
attached to it and is active.
This fix is applied for providers that support version 4 of the api.
https://bugzilla.redhat.com/show_bug.cgi?id=1447560
Please note: this PR will have an actual effect only when https://github.com/ManageIQ/manageiq/pull/15053 is merged.

Fix fetching ISO images from non active domains

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Add some specs to the reconfiguring vm process

Add specs for reconfiguring vm with OvirtSDK

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/strategies/api3.rb

When we target refresh for a host there is an issue when parsing
because parser code depends on availability of a cluster hash.
We fix this issue by fetching host cluster for this type of a refresh.
Bug:
https://bugzilla.redhat.com/1393942

Broken host targeted refresh

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher_builder.rb

When a provider is down there is incorrect message displayed on the UI.
The cause of it is that we are unable to get supported versions from a
server. This PR fixes error handling which provide meaningful message.
Bug:
https://bugzilla.redhat.com/1452157

Misleading message when provider is down

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/configuration/network.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb

Part of the PXE provisioning process which had to do with finding the mac address
was broken. It is now fixed and split between ovirt_services for v3 and v4.
https://bugzilla.redhat.com/show_bug.cgi?id=1454861

Fix provisioning PXE for version 4

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

The credentials verification process used the ovirt gem even when the
"use_ovirt_engine_sdk" setting was turned on.
In addition it was catching an exception that was defined in the ovirt gem.
Both issues are now fixed.

Remove dependence on ovirt-gem from credentials verification

---

app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb

When called from UI context (i.e. an appliance with only UI role) the provider
model may not see the actual RHEV instance (by not having the ems_operations
role). This may be a problem in complex production environments so here we do
the safe fallback - when the version is nil we mark the import as not
supported.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/1449

Use only cached version for vm import check

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/configuration/network.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb

This patch fixes some issues in oVirt vm provision network tab.
1. Changing the 'vLan' label to 'Network'
2. Displaying the vnic profiles instead of the host/hosts networks (only
profiles configured in the cluster).
3. Using OvirtSDK4.
Changes relevant to version 4 only.
Signed-off-by: Alona Kaplan <alkaplan@redhat.com>

ovirt-networking: using profiles

---

app/models/manageiq/providers/redhat/infra_manager/provision/disk.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/disk_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/state_machine_spec.rb

Datastores on the same setup may have the same name.
However, there is an assumption that datastores names on the same
provider are unique. The selection of datastore by its name should be
narrow to the provider on which the vm is provisioned.
https://bugzilla.redhat.com/show_bug.cgi?id=1427498

Select datastore by its association with the provider

---

app/models/manageiq/providers/redhat/infra_manager.rb

Fixed 'Datastore' from message to be aligned with its naming across the app.

Align datastore naming

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/parser.rb
spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb

This will allow `parse_new_target` to work with standard `save_ems_inventory`

Update parse_new_target to standard refresh hashes

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/vm/operations/guest.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1462803

Implement :reboot_guest for VM

---

app/models/manageiq/providers/redhat/infra_manager/metrics_capture.rb
spec/models/manageiq/providers/redhat/infra_manager/metrics_capture_spec.rb

When trying to collect C&U data from an Ovirt provider with missing credentials a warning will
be shown in the log but no exception will be risen.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1450644

Fix unhandled exception in metrics collection when missing credentials

---

app/models/manageiq/providers/redhat/infra_manager/vm/operations/snapshot.rb

Disable the delete button when the active snapshot is selected
for a vm on oVirt.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1443411
Required for: https://github.com/ManageIQ/manageiq-ui-classic/pull/1628

Disable delete button for the active snapshot on oVirt

---

manageiq-providers-ovirt.gemspec

Version 0.17.1 of the 'ovirt' gem fixes an issue with the Content-Type
and Accept headers sent to the oVirt server. See the following pull
request for details:
Use 'application/xml' explicitly
https://github.com/ManageIQ/ovirt/pull/83
This patch is related to the fix for the following bug:
Can't Provision Vm via V3 (using ovirt gem)
https://bugzilla.redhat.com/1466417

Use 'ovirt' >= 0.17.1

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/parser.rb
app/models/manageiq/providers/redhat/infra_manager/event_parsing/strategies/v4.rb

This will allow parse_new_target to work with standard save_ems_inventory
for v4 of the api
(for reference this is the PR that did it for v3: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/13)

Update parse_new_target to standard refresh hashes for v4

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/collector/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/target_response_yamls/disks.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/target_response_yamls/nics.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/target_response_yamls/snapshots.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/target_response_yamls/vms.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

Collector and parser implementations
RFE link: https://bugzilla.redhat.com/1466172

Graph refresh - target vm

---

app/models/manageiq/providers/redhat/infra_manager/host.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb

The patch adds support for host maintenance actions (activate
and deactivate host) to the host power operations.

Support host maintenance actions

---

app/models/manageiq/providers/redhat/infra_manager/vm_import.rb

When the "Install Drivers" option was unchecked an '' empty string value was
passed to the backend as the ISO name which resulted in an incorrect path being
sent to the RHV api, in turn causing a failure.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1467795

v2v: Normalize drivers_iso to nil on empty string

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/response_yamls/templates.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb

Remove getting the nics of templates during full refresh v4 and graph refresh.

Getting nics for templates is not required during refresh

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/configuration/container.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Memory limit feature was introduced in RHV 4.1.
It is already supported by manageiq as part of the vm provision process.
The patch adds support for total memory for providers of version 4.1 and
above, both for VM provision and for the VM refresh process.
https://bugzilla.redhat.com/show_bug.cgi?id=1461560

Support memory limit

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Currently when the user sets the TLS certification validation switch to
"Yes" and does not provide a custom CA certificate, the provider doesn't
trust the system CA certificates, it trust no certificates at all
instead. This isn't the intended behaviour. To address that issue this
patch changes the provider so that it sets the 'ca_certs' parameter to
'nil' in this case. That 'nil' value indicates to both the 'ovirt' and
'ovirt-engine-sdk' gems that the system CA certificates should be
trusted.
Note that when using version 4 of the API and the 'ovirt-engine-sdk'
gem, the system CA certificates are loaded only once, when the gem is
loaded. If any CA certificate is added to the system, then the affected
ManageIQ workers will need to be reloaded. The affected workers are all
the provider …

Use nil ca_certs to trust system CAs

---

app/models/manageiq/providers/redhat/infra_manager/vm.rb

During vm remove we used to call disconnect_storage. The first time
it was called as a first step of removal flow and during refresh.
This caused timing issue which caused lack of update to vm.ems_id.
As a result vm state was "unknown".
We need to make sure that disconnect_storage is called only once.
Bug-Url:
https://bugzilla.redhat.com/1468201

disconnect_storage should be called once

---

app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb

When network profiles were added, the default implementation of
filter_allowed_hosts was overridden.
The previous behavior used to return all of the hosts if couldn't
determine the vlan.
Same behavior should be maintained if there isn't ems available in the
context of the current selection.

Fixed hosts filtering when no ems selected

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/host_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb

This field used to be populated in v3 but we missed it in the new parser.
Added it back to v4 parser.

Fix missing number_of_nics on host hardware

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

2 problems fixed:
- allow to import only using 4.1.5+ provider.
The reason is that the required fix (https://bugzilla.redhat.com/1477375) is
present in 4.1.5+ and without this fix manageiq will wait until timeout
reached.
- check if submit to the provider succeeded.
The reason is that if the result is not checked, this state will always
succeed and the import will again wait until timeout.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1473169

Fixed cases causing waiting on timeout in vm_import

---

app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb

A template might loose its association with a provider when a template
is being removed from the provider. In that case the template will
become archived or orphan and its ext_management_system will return
nil.
The service catalog filters such vms or templates. However, an existing
service doesn't produce a meaningful error in such case.
Letting the service to allow nil value for EMS at dialog load will
produce a descriptive error when trying to provision.
https://bugzilla.redhat.com/show_bug.cgi?id=1471124

Fix allowed vlans to allow no provider

---

lib/manageiq/providers/ovirt/legacy/event_monitor.rb

It was added originally back in 2011 in manageiq:
946657b11a0a65abbcdca9975206d71f7c2b7afc
This was actually copied from the vmware vim monitoring events
code from 2009: 22a911716b40428b6d822f0f1e95aabd022e59c9
```
def monitorEvents
raise "monitorEvents: no block given" if !block_given?
trap(:TERM) { $log.info "monitorEvents: ignoring SIGTERM" }
...
```
First of all, trap with logging doesn't work since ruby 2.0+:
```
irb(main):001:0> require 'logger'
=> true
irb(main):002:0> trap(:TERM) { Logger.new("stdout").info
"EventMonitor#start: ignoring SIGTERM" }
=> "DEFAULT"
irb(main):003:0> `kill #{Process.pid}`
log writing failed. can't be called from trap context
=> ""
```
See https://github.com/ManageIQ/manageiq/pull/2386
Second, we need to TERM processes in container land.

Remove seemingly unnecessary ignoring of SIGTERM

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/vm.rb

The way it was done before is by checking for an exception when refreshing the vm.
This is part of a fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1478108
This is required for: https://github.com/ManageIQ/manageiq-automation_engine/pull/66

Add method to check if vm exists on provider

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb

Don't update the ems directly from the refresh_parser
~~Depends: https://github.com/ManageIQ/manageiq/pull/15252~~

Parse ems attributes like normal inventory

---

app/models/manageiq/providers/redhat/infra_manager/vm.rb

RHV doesn't support VM reset action and should block it when VMs are
being selected for reset via the VMs center dialog.
https://bugzilla.redhat.com/show_bug.cgi?id=1476592

Block unsupported VMs reset

---

manageiq-providers-ovirt.gemspec

Version 0.18 or newer of the 'ovirt' gem is needed in order to work
correctly with custom TLS trusted CA certificates.
This patch addresses the following bug:
Service order request for VM provision from template fail on SSL Certificate verification
https://bugzilla.redhat.com/1483303

Require version 0.18 or newer of ovirt gem

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/api4.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Commit https://github.com/ManageIQ/manageiq-providers-ovirt/commit/3e2cdfc412a72c12cb88557dbb5ae585c8834229 introduced an update of the `ems_version` during the refresh, to avoid updates to the ems during the parsing. However, fetching the ems_api_version should be done differently for v3 and v4.
The PR also supports the following cases for graph refresh:
1. Empty data-center in clusters or hosts
2. Host network interfaces without a network configured on top

Fix handling of version-depended refresh

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision.rb
app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_via_iso/state_machine_spec.rb

Currently the provisioning of virtual machines from templates using
cloud-init fails when using version 4 of the API. The reason is that the
'update_cloud_init!' method used to set configure cloud-init isn't
implemented for that version of the API. This patch implements it,
preserving the logic used in the implementation done for V3, as we need
to make sure that existing customization scripts will continue working.
This patch is part of the fix for the following bug:
Cloud-init not working when using api v4
https://bugzilla.redhat.com/1486340

Implement 'update_cloud_init' for V4

---

config/settings.yml

These settings will be removed from the core repo in a separate PR.
The settings in the provider repo override the once in the core repo
in case a setting is defined in both.

Move oVirt settings to the oVirt provider repository

---

config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb

use_ovirt_engine_sdk will now be set to true by default.
https://bugzilla.redhat.com/show_bug.cgi?id=1490091

Use the new ovirt_sdk by default

---

app/models/manageiq/providers/redhat/connection_manager.rb
app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
config/settings.yml
spec/models/manageiq/providers/redhat/connection_manager_spec.rb

This patch adds a new `ConnectionManager` singleton intended to simplify
re-use of connections in single threaded processes. This class will
manage a set of connections, indexed by the identifier of the EMS. The 
connections will be created when needed, re-created when options change,
and closed when the worker finishes or when the EMS is removed from the 
database.
Checking for removed EMSs is performed periodically, with an interval
controlled by the new `connection_manager.purge_interval` parameter. The 
default value is 1 hour:
```yaml
:ems:
:ems_ovirt:
:connection_manager:
:purge_interval: 1.hour
```
The existing code is also changed so that it uses the connection manager
instead of creating the connections directly, and so that it does not 
close the connections explicitly.
This …

Add connection manager

---

config/settings.yml

@borod108 @jhernand @pkliczewski please have a look at the individual commits
whats still missing is `event_handling`. This would involve identifying the redhat events in the core settings and moving them here.
```shell
~/src/manageiq-content/content/automate/ManageIQ 
❯ pwd
/Users/hild/src/manageiq-content/content/automate/ManageIQ
~/src/manageiq-content/content/automate/ManageIQ 
❯ ag name System/Event/EmsEvent/RHEVM.class/
```

move provider specific settings over here

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
app/models/manageiq/providers/redhat/infra_manager/provision/state_machine.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
app/models/manageiq/providers/redhat/infra_manager/vm.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb

Creating a template from a VM is supported by RHV since forever.
The PR introduces a new dialog to allow the creation of a template from
a VM, including the ability to seal a template (for non-windows vms).
https://bugzilla.redhat.com/show_bug.cgi?id=1373076
**Screenshots of the new dialog:**
Request tab:
Catalog tab:
Environment tab:
Schedule tab:
Due to a limitation of RHV, when specifying a storage domain, all of the template's disks will be created on the specified storage domain (while on RHV the user can specify storage domain per disk)

Support publish VM

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/futures_collector.rb
app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/futures_collector_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/support/ovirt_sdk/connection_vcr.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/inventory/strategies/v4/collect_disks.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml

Make full refresh through OvirSDK use asynchronous calls to oVirt to improve performance.
This should make the refresh significantly faster
https://bugzilla.redhat.com/show_bug.cgi?id=1404346

Make full refresh through OvirSDK use asynchronous calls to oVirt

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Resolves uninitialized constant error described in https://github.com/ManageIQ/manageiq-providers-ovirt/pull/67
@miq-bot assign @borod108 

Require Ovirt in ApiIntegration

---

app/models/manageiq/providers/redhat/builder.rb
app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v3.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/inventory/collector/network_manager.rb
app/models/manageiq/providers/redhat/inventory/parser/network_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/network_manager.rb
app/models/manageiq/providers/redhat/inventory_collection_default/network_manager.rb
app/models/manageiq/providers/redhat/network_manager.rb
app/models/manageiq/providers/redhat/network_manager/cloud_network.rb
app/models/manageiq/providers/redhat/network_manager/cloud_subnet.rb
app/models/manageiq/providers/redhat/network_manager/event_catcher.rb
app/models/manageiq/providers/redhat/network_manager/event_catcher/runner.rb
app/models/manageiq/providers/redhat/network_manager/event_parser.rb
app/models/manageiq/providers/redhat/network_manager/metrics_capture.rb
app/models/manageiq/providers/redhat/network_manager/metrics_collector_worker.rb
app/models/manageiq/providers/redhat/network_manager/metrics_collector_worker/runner.rb
app/models/manageiq/providers/redhat/network_manager/network_port.rb
app/models/manageiq/providers/redhat/network_manager/refresh_parser.rb
app/models/manageiq/providers/redhat/network_manager/refresh_worker.rb
app/models/manageiq/providers/redhat/network_manager/refresh_worker/runner.rb
app/models/manageiq/providers/redhat/network_manager/refresher.rb
config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/response_yamls/external_network_providers.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/target_response_yamls/external_network_providers.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Discovering OVN as the network provider of oVirt and supporting showing
ports and CRUD actions for networks and subnets.
Manageiq will communicate directly with ovirt-provider-ovn.
Since ovirt-provider-ovn has neutron like api as much as possible
openstack's network provider code was reused.
Feature page -
https://github.com/oVirt/ovirt-site/pull/1068

Introducing OVN as oVirt's network provider

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

We need to make sure that any errors during ovirt credentials validation are properly
propagated to the user.

Propagate user validation errors

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb

Currently the constructor of the `TemplatePreloadedAttributesDecorator`
class receives a parameter that defaults to 'nil', and that it is
actually never used. But the implementation of the constructor tries
call methods on it, `NoMethodError`. The net result is that refresh
fails. To avoid that this patch removes that unused parameter.
This patch addresses the following issue:
RHV Refresh worker throwing error in evm.log
https://bugzilla.redhat.com/1501162

Avoid NoMethod error in TemplatePreloadedAttributesDecorator.new

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/host_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb

Parse the serial number of host during refresh.
This is required for:
https://bugzilla.redhat.com/show_bug.cgi?id=1410183
Required for:
https://github.com/ManageIQ/manageiq/pull/15992

Parse the serial number during refresh

---

manageiq-providers-ovirt.gemspec

This patch changes the provider so that it directly requires version
4.1.9 or newer of the oVirt Ruby SDK.
The new version of the SDK addresses a problem when using the same
connection from multiple threads, described in the following bug:
Access to RHV using the oVirt SDK may crash the events worker
https://bugzilla.redhat.com/1496848

Require oVirt Ruby SDK 4.1.9 or newer

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/supported_apis_mixin.rb
config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

The probing for api versions was done by connecting to the provider directly
which causes problems when done from a UI applience which has no access to the
provider.
We now use the "api_version" (which actually contains the product version)
to infer the api version supported. When the feild is not available we try probing.

Move detecting the api versions to database query

---

content/service_dialogs/transform-vm.yml

This column was recently removed, but this shouldn't have been here anyway
$ rake db:seed
** ManageIQ master; Database: adapter=postgresql, name=vmdb_development, host=
** Using session_store: ActionDispatch::Session::MemCacheStore
rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'blueprint_id' for Dialog.
/home/bdunne/.gem/ruby/2.3.3/gems/activemodel-5.0.6/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/home/bdunne/.gem/ruby/2.3.3/gems/activemodel-5.0.6/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/home/bdunne/.gem/ruby/2.3.3/gems/activemodel-5.0.6/lib/active_model/attribute_assignment.rb:39:in `each'
/home/bdunne/.gem/ruby/2.3.3/gems/activemodel-5.0.6/lib/active_model/attribute_assignment.rb:39:in …

ID's shouldn't be in the service dialog YML

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb

Fill VmOrTemplate relation correctly, in Targeted refresh
we were seeing this reference as missing.

Fill VmOrTemplate relation correctly

---

content/service_dialogs/transform-vm.yml

Added tag category and tag name fields to the 'VM Transform' dialog to
be able to select VMs for V2V by tag. Hide these fields if the dialog is
open from VM details view. Hide VM name input field if the dialog is
open from VM list view.
Depends on https://github.com/ManageIQ/manageiq-content/pull/200
Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/2501

v2v: Extend 'VM Transform' dialog to select VMs by tag

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
manageiq-providers-ovirt.gemspec

The provider has two configuration settings that control timeouts:
read_timeout - Max time to wait for a response.
open_timeout - Max time to wait for a connection.
Both parameters are honoured when using version 3 of the API, but only
the first one is honoured when using version 4 of the API. The result is
that trying to connect to a wrong IP address doesn't fail after
`open_timeout`, but after the default used by the SDK for this, which is
300 seconds (that is the default used by the underlying library).
To avoid that this patch changes the provider so that it uses the
version of the SDK that supports the new `connect_timeout` parameter
(version 4.1.10) and so that it copies the `open_timeout` configuration
setting into the `connect_timeout` parameter of the SDK.
This patch addresses …

Honour `open_timeout` when using V4

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb

When a vm is newly created there are only few attributes so graph targeted refresh
need to handle this use case.
Bug-Url:
https://bugzilla.redhat.com/1508465

Handle partial vm entity during creation

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/vm/operations/snapshot.rb
spec/models/manageiq/providers/redhat/infra_manager/operations/snapshot_spec.rb

The management of the connectios to the oVirt server is the exclusive
reponsibility of the `ConnectionManager` class. Nothing else should
create or close connections, otherwise callers may end up receiving
closed connections.
This patch changes two places in the provider that are explicitly
closing connections.

Don't close connection explicitly

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb

It seems like vm removal never worked for apiv4.
Bug-Url:
https://bugzilla.redhat.com/1509020

Fix vm removal for apiv4

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Currently the `raw_connect` method needs to receive the version of the
API in order to work correctly. If it doesn't receive it it fails
because the method that determines it just doesn't exist (it is an
instance method, but `raw_connect` is a class method). To avoid that
this patch changes the `raw_connect` method so that it tries with both
versions of the API.
This patch fixes partially the following bug:
Failed validation when adding RHV provider
https://bugzilla.redhat.com/1509432

Try both API versions in `raw_connect`

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Currently the `raw_connect` doesn't check the metrics connection
details. This patch adds that check.
This patch fixes partially the following bug:
RHV provider metrics validation is broken
https://bugzilla.redhat.com/1510533

Check metrics details from `raw_connect`

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

If no metrics credentials are given the metrics_server is "" not nil.
This was causing it to continue past the `return true unless server`
line and fail later on.
This checks if the metrics_server is `.blank?` which will catch nil as
well as "".
Introduced by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/134

Fix credential validation if no metrics given

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/strategies/v4.rb

EmsEvent do not contain `:vm_location` which prevents reconnect_events to be run due to [this](https://github.com/ManageIQ/manageiq/blob/master/app/models/vm_or_template.rb#L821).
Bug-Url:
https://bugzilla.redhat.com/1510459

Vm provisioning do not run reconnect_events

---

content/service_dialogs/transform-vm.yml

Set tag category in 'Transform VM' dialog to 'Migration Groups' by
default.
Depends-on: https://github.com/ManageIQ/manageiq/pull/16402

Set default tag category in 'Transform VM' dialog

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/host_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb

The host 'maintenance' attribute was added to provision vm dialog
by https://github.com/ManageIQ/manageiq/pull/16464 and tracked by https://github.com/ManageIQ/manageiq-providers-ovirt/issues/141
RHV should store this information which is already available during host
refresh.
https://bugzilla.redhat.com/show_bug.cgi?id=1513413

Save host 'maintenance' value

---

manageiq-providers-ovirt.gemspec

The more relevant changes in this version of the oVirt Ruby SDK are the
following:
* Virtual machine remove fails due to spelling mistake
https://bugzilla.redhat.com/1509020[#1509020].
* Improve error message for empty response body
https://bugzilla.redhat.com/1509020[#1509020].
* Don't send `Expect: 100-continue`
https://bugzilla.redhat.com/1509910[#1509910].
* Don't include sensible data in the result of `inspect` and `to_s`
https://bugzilla.redhat.com/1513620[#1513620].
This change addresses the following issue:
Evm.log contains passwords
https://bugzilla.redhat.com/1512977

Use version 4.1.13 of the oVirt Ruby SDK

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/admin_ui.rb

This PR is part of the following series:
- [Add ems_infra_admin_ui feature](https://github.com/ManageIQ/manageiq/pull/16403) (manageiq)
- [Add ems_infra_admin_ui feature support](https://github.com/ManageIQ/manageiq-ui-classic/pull/2644) (manageiq-ui-classic)
- **[Add admin_ui feature support to InfraManager](https://github.com/ManageIQ/manageiq-providers-ovirt/pull/133) (manageiq-providers-ovirt)**
Utilize `admin_ui` feature in `InfraManager`, using `AdminUI` concern to contain the URL generation logic.
URL to access oVirt WebAdmin is generated in two steps:
1. obtain new SSO token from oVirt Engine, using the credentials of the provider
2. construct URL to access WebAdmin, using the SSO token obtained in the previous step
This PR currently relies on Ravi's [Engine …

Add admin_ui feature support to InfraManager

---

app/models/manageiq/providers/redhat/infra_manager.rb

This PR enables `admin_ui` feature support for Engine version >= 4.1.8 ([BZ link](https://bugzilla.redhat.com/1512989)).

Update Engine version check for admin_ui feature

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

`ManageIQ::Providers::Redhat::InfraManager#version_higher_than` method performs >= comparison, this PR renames it to `version_at_least`.

Rename version_higher_than to version_at_least

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb

When a host was targeted when using graph refresh it was deleted after the operation
due to missing data being collected from the provider.

Fix target host

---

app/models/manageiq/providers/redhat/infra_manager.rb

`version_higher_than` was renamed to `version_at_least` via [another PR](https://github.com/ManageIQ/manageiq-providers-ovirt/pull/143) and I forgot to sync with code that implements the `admin_ui` feature 😞

Fix version check in supports_admin_ui method

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/update_cloud_init_spec.rb

The change that implemented cloud-init with version 4 of the API
introduced an error in the handling of custom cloud-init scripts: all
the cloud-init attributes are transformed into Ruby symbols, thus they
have a leading `:` character that cloud-init does not understand. For
example, if the following cloud-init customization template is used:
#cloud-config
write_files:
- path: /tmp/test.txt
content: |
Here is a line.
Another line is here.
permissions: '0755'
It will be translated into the following *incorrect* cloud-init custom
script:
:write_files:
- :path: "/tmp/test.txt"
:content: |
Here is a line.
Another line is here.
:permissions: '0755'
To fix that this patch changes the `update_cloud_init!` method so that
it does the conversion from strings to symbols only for the attributes
that …

Handle correctly custom cloud-init script

---

spec/i18n/placeholders_spec.rb

This is just invocation of standard i18n placeholder test, included from main ManageIQ
repository. It's the same thing that we do in ui-classic to test that the provided translations
honor placeholders in the original (English) strings.

Add i18n strings placeholders test

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

The `raw_connect` method of providers is intended to check connection and authentication details.
This method should report errors throwing instances of `MiqEVMLoginError`, `MiqInvalidCredentialsError`, etc.
This fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1510374

Raise Miq exceptions on connect

---

app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb

At the moment it is not possible to update ems during graph refresh
so we need to introduce this hack to enable version based functionality.
Bug-Url:
https://bugzilla.redhat.com/1517865

Update ems version during graph refresh

---

app/models/manageiq/providers/redhat/infra_manager/supported_apis_mixin.rb

Before, when an instance of the ext_management_system was memoized before api_version is set would probe the provider again and again to get list of available versions.
Now it checks if api_version is available in db and reloads it if so.
This fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1512490

Reload provider when api_version available

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/strategies/api3.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/strategies/api4.rb

Since we can create template from MIQ side on RHV, templates should be
fully refreshed once the creation is completed.
In addition, when a template is being created on RHV side, not all of
its fields are being updated.
Therefore, there is a need to support also template target refresh
(unrelated to graph refresh in this context).
Fixes bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1517852

Implement template targeted refresh

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb

Due to latest rename of property name in publish vm yaml file from :seal
to :seal_template, sealing option wasn't processed properly.
In addition, the property should be send as part of the request header,
therefore should be specified in the second parameter of the
`templates_service.add(template, :seal => options[:seal])` method.
https://bugzilla.redhat.com/show_bug.cgi?id=1514895

Fix Seal option of publish VM

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/strategies/v4.rb

When ever a host is targeted event parsing fail since it is not possible to
build `vm_location`. We make sure that it is not calculated when targeting a host.
Bug-Url:
https://bugzilla.redhat.com/1520513

Targeting host fails

---

app/models/manageiq/providers/redhat/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Each service catalog now requires the provider to provide a list of supported catalog types.
This is part of PR https://github.com/ManageIQ/manageiq/pull/16559

Added supported_catalog_types

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

The `pipeline` and `connections` settings are in the following path:
```
:ems_refresh:
:rhevm:
:pipeline: 40
:connections: 10
```
But the part of the code that creates the SDK connection gets them from
a different place. As a result the parameters arent really applied, and
the number of connections is unlimited. When combined with the settings
used by the asynchronous refresh code, this results in the creation of
hundreds of connections. When there are more than 256 connections open
the oVirt server will start rejecting them, and the refresh fails.
This patch fixes the location of the parameters in the code that creates
the SDK connection.
Fixes https://bugzilla.redhat.com/1513528

Fix location of `pipeline` and `connections` settings

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb

- One network device per nic and not per address.
- The patch also fixes the guest_device to network association.
Affected flows - full graph refresh and regular refresh v4.
Regular refresh v3, left untouched.
Bug-Url: https://bugzilla.redhat.com/1511580

Store ipv4/ipv6 of guest devices aligned to vmware implementaion

---

manageiq-providers-ovirt.gemspec

The more relevant changes in this new version of the SDK are the
following:
* Fix handling of the `all_content` parameter
https://bugzilla.redhat.com/1525555[#1525555].
* Limit the number of requests sent to `libcurl`
https://bugzilla.redhat.com/1525302[#1525302].
Fixes https://bugzilla.redhat.com/1513528

Update to version 4.2.1 of the oVirt Ruby SDK

---

spec/support/ovirt_sdk/connection_vcr.rb

The ConnectionVCR did not save multiple results for the same request,
it saved only the result of the last one which did not allow to record
several refreshes.
This fixes the bug so now several refreshes can be recorder and played
back.

Fix ConnectionVcr recording

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb

We need to make sure that when we remove a provider and add it again we
will keep using the same host entities. Without this change add and remove
provider cause to duplicate hosts.
Fixes https://bugzilla.redhat.com/1528859

Reconnect host on provider add

---

app/models/manageiq/providers/redhat/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

We need to align migration call semantic with vmware. We want to block
the call and return with success or raise an error.
Fixes https://bugzilla.redhat.com/1448023

Block migration call

---

app/models/manageiq/providers/redhat/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Fix wrong call to 'orchestrate_destroy' with no parameters
'orchestrate_destroy' was changed recently to take parameters, the change
caused the removal of network provider flow to get an exception.

Fix wrong call to 'orchestrate_destroy' with no parameters

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb

Currently the SSA tries to use v4 when working with providers that support
v4.
The code in ssa was not changed to work with v4 which causes a bug.
A future PR will allow it to work with v4 but currently we will force it
to work with v3.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1534502

Force smart state analysis to use V3

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/host.rb
app/models/manageiq/providers/redhat/infra_manager/vm.rb

This is a continuation of the work started in https://github.com/ManageIQ/manageiq/pull/16596 where we want to migrate display model names from locale/en.yml into particular models, where we'll use standard gettext. Main goal here is to make this one aspect of our application pluggable.
Core PR: https://github.com/ManageIQ/manageiq/pull/16836

Migrate model display names from locale/en.yml to plugin

---

app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb

When the provider is removed updating the catalog item would fail
because we validate if provider supports setting memory limits.
We now by default decide we do not support it if the provider is was
removed. A more elaborate fix will be discussed on the core
level.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1540592

Fix updating catalog item when provider missing

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/strategies/v4.rb

We were not adding vm_location correctly to the event hash when
the dc in the event was blank.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1537139

Fix adding vm_location to vm event hash

---

app/models/manageiq/providers/redhat/discovery.rb

https://github.com/ManageIQ/manageiq/pull/16994

Update client to use renamed NetworkDiscovery

---

app/models/manageiq/providers/redhat/discovery.rb

Reflect change in Discovery core introduced in https://github.com/ManageIQ/manageiq/pull/16994.

Discovery namespace change

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

When refresh is set to use graph strategy we should still use old
refresh in case the provider does not support version 4 of the api.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1540475

Use correct refresh for older providers

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb

The targeted spec would take a very long time because the requests
actually failed.

Fix graph targeted host refresh spec

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml

Graph refresh fixed to fetch the custom attributes for both full and targeted refresh.
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1546792

Fix graph refresh fetching custom attributes

---

spec/models/manageiq/providers/redhat/infra_manager/event_catcher/runner_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb

Fix spec tests which relied on our custom have_attributes extensions
which were removed here https://github.com/ManageIQ/manageiq/pull/17021

Fix spec tests without have_attributes extensions

---

config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_after_publish_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

Graph refresh is now used for both full and targeted refresh.

Make graph refresh enabled by default

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/vm/operations.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb

Unregister VM allows the user to remove the VM without deleting its
disks.
For that purpose, the request to remove VM to ovirt-engine includes the
'detach_only=true' parameter as specified in the [API](http://ovirt.github.io/ovirt-engine-api-model/master/#services/vm/methods/remove)
This action will succeed if the VM isn't originated from a template, or
if the VM has no snapshots.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536628

Support Unregister VM

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

Since ManageIQ doesn't support max memory, there is a need to provider a
value for it when modifying the vm memory limit.
The max memory will be calculated as follow:
1. Fetch actual VM from RHV to get current max memory
2. If new actual memory is higher than existing max memory, the max memory will
be updated as well:
a. If actual memory is lesser than 1 TB, then set max memory to 4 * actual memory
b. If actual memory equals or greater than 1TB, set max memory the same value as
actual memory
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534520

Provide max memory on VM reconfigure

---

app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb

A duplicated method definition lead to spec failures.

[GAPRINDASHVILI] Fix broken spec

---

spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml

Fix broken tests caused by fog-openstack upgrade
The fix was done on the provider side and a cassette was re-recorded.

Fix broken tests caused by fog-openstack upgrade

---

app/models/manageiq/providers/redhat/discovery.rb

Due to moving the provider discovery code, "Ovirt" was evaluated to
ManageIQ::Providers::Ovirt.
It should evaluate to the Ovirt Model defined in the ovirt-gem.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1559796

Fix provider discovery

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml

We will now fetch the snapshot current state from the snapshot_type returned
form the oVirt api, the previous calculation we used for this attribute did not
always work.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1552732

Properly fetch snapshot current state

---

config/settings.yml

Use the old refresh as default since graph refresh is not optimized for
large environments yet.
This is due to: https://bugzilla.redhat.com/show_bug.cgi?id=1566468

Use old refresh as default

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
spec/support/ovirt_sdk/connection_vcr.rb

The connection_vcr will now raise an error if it is not in recording
mode and a response is missing.
This will make tests fail faster, on a clearer error and not rewrite a
recording in cases when it has a request missing.

Raise error during test if response is missing

---

app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb

Improve the performance of the ems_folders_children and ems_clusters_children custom save blocks.
Note: link_ems_inventory is equivalent to the sum of ems_folder_children and ems_cluster_children save blocks.
Tested against a live scale environment with three configurations:
master - legacy ems_refresh
save_inventory: 250.93 sec
link_ems_inventory: 27.698 sec
master - graph refresh
save_inventory: 421.19 sec
ems_folder_children + ems_cluster_children: 286.32 sec
this pr - graph refresh
save_inventory: 196.86 sec
ems_folder_children + ems_cluster_children: 46.89 sec
The graph refresh link_ems_inventory equivalent was significantly slower than the ems_refresh link_ems_inventory, but not enough so that it drowned out the rest of the graph refresh improvements allowing graph refresh to still …

Improve performance of EmsFolders and EmsClusters child save blocks

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb

Consolidate the vm/host/root folder collections into a single standard ems_folders collection and rewrite ems_clusters_children to do a single query for all clusters and save in a single transaction instead of a transaction per cluster.

Ems metadata improvements

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml

Avoid refreshing the vm a second time if snapshot was removed.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1571291
depends on https://github.com/ManageIQ/manageiq/pull/17462

Fix refreshing targeted vm after snapshot removal

---

app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb

Improve readability of configure_cloud_init, follow-up from https://github.com/ManageIQ/manageiq-providers-ovirt/pull/247#discussion_r189962435

Set EMS api_version to a variable for readability

---

app/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/api4.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/host_inventory.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
app/models/manageiq/providers/redhat/inventory/collector.rb
app/models/manageiq/providers/redhat/inventory/collector/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_publish_vm_to_template.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_for_mod.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_target_template_disconnect.yml

The 'lan' table contains a mapping of the the networks attached to the
hosts.
If a vm is running, vm.hardware.nics[i].lan should return the host network
it is attached to.
There are two reasons it wasn't working -
1. host_inventory didn't store the same instance of the lan in the 'hash'
and in 'lan_uids'.
Since the vm_inventory used the 'lan_uids' instance, it didn't get the
id of the lan once it was stored to the db (the id was updated on the
'hash' instance).
2. The vnic (vm nic) returned by the ovirt sdk doesn't contain the network
name (the value is always null). The network should be retrieved using the
vnic profile.
* Similar fixes were done to the relevant files in graph refresh.
* v3 wasn't fixed.
Fixes https://bugzilla.redhat.com/1572917

vm.hardware.nics[i].lan should return the network attached to the vm

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb

Accept 'profile_name (network_name)' as a valid vlan of vm provision
'profile_id' or 'profile_name (network_name)' are both acceptable.
Fixes https://bugzilla.redhat.com/1574351

Profile description

---

app/models/manageiq/providers/redhat/infra_manager/event_parsing/parser.rb

The log would fail on new events when set to debug level.
As a result refresh would not run and provider not updated.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1580521

Fix logging oVirt event in debug level

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Currently we do not validate ssh keypair on rhev. It should always
return true for ssh_keypair type authentication.
This is part of the pull requests that solve: https://bugzilla.redhat.com/show_bug.cgi?id=1561353

RHEV SSH Keypair auth always returns true

---

app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb

Remove the useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472

Remove useless EmsRefresherMixin

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

Pass hash to find_by instead of string.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1593202

Fix refresh failing on guest device lan collection

---

app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb

The full refresh persister was using the :vm_and_template_ems_custom_fields
association but the targeted persister was using the :custom_attributes
association.  This caused targeted refresh to clear all
miq_custom_attributes which were added outside of refresh.

Use the same assoc for targeted and full refresh

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml

Targeted graph refresh on deleted vm would fail.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1592430

Fix vm targeted refresh on removal

---

app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb

The full refresh persister was using the :vm_and_template_ems_custom_fields
association but the targeted persister was using the :custom_attributes
association.  This caused targeted refresh to clear all
miq_custom_attributes which were added outside of refresh.
Master PR: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/265
https://bugzilla.redhat.com/show_bug.cgi?id=1594833

[GAPRINDASHVILI] fix miq custom attributes deleted

---

app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb

Fix an issue where targeted refresh is clearing other VM's
ems_custom_attributes
Test taken from https://github.com/ManageIQ/manageiq-providers-ovirt/pull/270

[GAPRINDASHVILI] Fix targeted refresh clearing other VMs ems_custom_attrs

---

app/models/manageiq/providers/redhat/inventory/persister/definitions/network_collections.rb

**Issue**: https://github.com/ManageIQ/manageiq/issues/17396
Method rename `add_builder_params` => `add_default_values`

Persister: optimized InventoryCollection definitions

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

We were calculating the disk_type based on the sparse property of the
disk. This is incorrect, it should actually be calculated based on the
format property.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1598747

Fix disk_type attribute

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb

We ignored the clone_type parameter during provisioning from template.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1598747

Fix provisioning independent VM

---

app/models/manageiq/providers/redhat/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

VMware provider has support to set VM memory and number of CPUs. This PR adds the same same methods to oVirt provider. The implementation relies on `vm_reconfigure` which already implements the logic.
Blocks: https://github.com/ManageIQ/manageiq-automation_engine/pull/216
Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1623021

Add support to set VM memory and number of CPUs

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Support for disconnecting after an operation is now in the core, so there is no need to copy-paste the whole with_provider_connection function anymore.
Depends on https://github.com/ManageIQ/manageiq/pull/17959
@miq-bot add_label wip

[WIP] Use core's disconnect hook

---

spec/models/manageiq/providers/redhat/infra_manager_spec.rb

Fixing a test that was broken due to a PR that added validation to zone
when putting a task into MiqQueue. (https://github.com/ManageIQ/manageiq/pull/17987)

Fix broken spec

---

app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb

Add sysprep specification support for vm provisioning from template
for the oVirt provider.
Depends on: https://github.com/ManageIQ/manageiq/pull/17636
Required for: https://github.com/ManageIQ/manageiq-ui-classic/pull/4211
Implements: https://bugzilla.redhat.com/show_bug.cgi?id=1553833

Add sysprep support for ovirt

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb

We discovered an issue with oVirt targeted host refresh which led to lans being cleared.  We proceeded to discover more issues:
After a targeted refresh of a host:
1. Lans would be deleted
2. An extra cluster was created
3. Extra networks were created
4. Storages were duplicated
5. HostStorages were being duplicated and failing on duplicate key constraints
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1619431

[GAPRINDASHVILI] fix targeted refresh

---

app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb

If the [get_source_and_targets[:vm]](https://github.com/ManageIQ/manageiq/blob/master/app/models/miq_provision_virt_workflow.rb#L394) fails, the [source_vms](https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb#L163) will be nil and maybe we could just use the safe op thingy?
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633540

Add safe operator for bz 1633540 to protect against empty source_vms

---

app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb

Method from core was overridden without an optional parameter which broke
the PXE provisioning.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1633516

Fix PXE provisioning

---

app/models/manageiq/providers/redhat/discovery.rb
spec/models/manageiq/providers/redhat/discovery_spec.rb

Note, Ovirt namespace exists in the client gem and also in the
ManageIQ::Providers namespace so we need to clarify which Ovirt we want,
namely, the ovirt gem's one.
We had a regression and tests didn't detect it:
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/208
https://github.com/ManageIQ/manageiq/pull/16994

Add missing probe test

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb

The type of the payload was not passed.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1613326

Fix attach_floppy to pass "floppy" type

---

app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb

Overriding function in the provider did not account for the case when
prepare_customization_template_substitution_options custom template is not provided.
Added handling for that case.
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1633516

[WIP] Fix pxe provisioning

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

So we can reuse applying connection defaults in other places.

Refactor connection method

---

app/models/manageiq/providers/redhat/ansible_role_workflow.rb
spec/models/manageiq/providers/redhat/ansible_role_workflow_spec.rb

When a CA string is passed as an extra_var create a temporary directory
and in it create a file with the string as its content.
Pass the path of the file as the engine_cafile to the Ansible role.
This is part of implementing: https://bugzilla.redhat.com/show_bug.cgi?id=1644605

Add support for CA for Ansible role

---

app/models/manageiq/providers/redhat/infra_manager/vm.rb

Core is going to call disconnect_storage from disconnect_inv so no need
to override it.
Depends: https://github.com/ManageIQ/manageiq/pull/18200
https://bugzilla.redhat.com/show_bug.cgi?id=1644770

No need to override disconnect_inv from core

---

spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb

* dependent: https://github.com/ManageIQ/manageiq/pull/17452
Some specs limits MiqRegion not to receive maintenance_zone method, needs to be updated.
cc @agrare

EMS validation with maintenance zone specs fix

---

app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb

Instead of calling inventory.inventory_collections and return an array
of inventory collections, convention is to call inventory.parse and
return a persister which is handled easier by the subsequent
save_inventory method.

Fix parse_targeted_inventory to call inv.parse

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_collections.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb

Use a standard lazy_find for the snapshot parent link instead of a
custom saver.

Replace custom snapshot_parent saver

---

app/models/manageiq/providers/redhat/inventory/persister.rb

The shared_options were duplicated from the base persister

Remove duplicated persister shared_options

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

When cloning the template base the disk name on the vm name. So the disk
name will be "<vm_name>_Disk<number_of_disk>".
Implements: https://bugzilla.redhat.com/show_bug.cgi?id=1662489

When cloning template base disk name on vm name

---

app/models/manageiq/providers/redhat/infra_manager/host.rb
spec/models/manageiq/providers/redhat/infra_manager/host_spec.rb

This sets `supports :conversion_host` to the Host model.
The main purpose for this is for the ManageIQ REST API, where support for `conversion_host` will be checked before attempting to enable or disable the resource.
Part of the V2V effort.

Add supports_conversion_host to Host

---

app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/networks_collections.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml

https://bugzilla.redhat.com/show_bug.cgi?id=1669176

Host targeted refresh deleting and re-creating storage, switch, and lan records

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb

This reverts commit a0002db568b408bf57877489994465ecc6146909.
Upon further discussion with the storage team it seems that the initial
way of setting the disk_type was right, and did not work correctly in
some cases due to oVirt side bug.

Revert "Fix disk_type attribute"

---

app/models/manageiq/providers/redhat/infra_manager/conversion_host.rb
app/models/manageiq/providers/redhat/infra_manager/service_template_transformation_plan.rb

For the V2V effort, we will want subclasses for both the ConversionHost and ServiceTemplateTransformationPlan models. For now these are just stubs, but the plan is to add additional logic in the future.
For the ConversionHost model, this will likely contain provider-specific authentication code. At the moment, we have some ugly provider-specific code baked into the core ConversionHost model, which I would like to polymorphosize (if that's a word).
For the ServiceTemplateTransformationPlan model, this will contain provider-specific mapping validation code.
Both underlying tables (conversion_hosts and service_templates) are already setup for STI.

Add ConversionHost and ServiceTemplateTransformationPlan subclasses

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb

When comparing whole tables we need to sort by id, this was done with
`#sort` instead of `#sort_by` leading to sporadic failures.
Example: https://travis-ci.org/ManageIQ/manageiq-providers-ovirt/jobs/497964470

Fix sporadic test failure on sorting IDs

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/cluster_collections.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb

Fixes the ems_cluster reference from hosts and vms on RHV 4.3 where the cluster href (and thus ems_ref) is of a different format from what can be seen from the vm/host.
The cluster.id is always consistent however which maps to the uid_ems, so we can use a secondary ref index to lazy find the cluster by the id instead of href.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1668720

Skip VMs missing a cluster when saving relats

---

app/models/manageiq/providers/redhat/infra_manager/vm.rb

User story:
"VM don't change power_state until BitLocker password not entered
but if you want enter BitLocker password, you need access to HTML5 console
and if power state unknown HTML5 console is unable
if we are mapped 'powering_up' to 'on' it's solve this problem"

mapping from "powering_up" to "on"

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

Removing a disk was not handled correctly
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1666593

Fix deleting a disk from VM

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/host_inventory.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb

Retrieving ipmi from host is not relevant for rhv anymore due to the
current complexity of fencing so it does not make sense to get it from
the provider.
However if it is set manually by the user, it should not be deleted.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1669011

Fix refreshing ipmi from host

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb

Prevent duplication of host guest_devices by using the correct
association.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1691109

Use the host_geust_devices inventory collection

---

app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
app/models/manageiq/providers/redhat/inventory/collector/network_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb

Wanted to get the conversation started here with @borod108 and @aufi
Is this an appropriate solution for both ovirt and openstack?
@borod108 I'd like to add a rhv version check, something like:
```
def security_groups
manager.api_version > 4.2.6 && manager.api_version < 4.3 ? [] : super
end
```
Can you help with the correct versions to check for there?
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649886

Don't collect security groups in rhev refresh

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml

When a vm would have several network reported devices and one of them
would not have an ipaddress we would not get the ips from all the
devices that come after it.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1686884

Fix refreshing vm ips - multiple reported devices

---

app/models/manageiq/providers/redhat/dialog_field_visibility_service.rb
app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
app/models/manageiq/providers/redhat/linked_clone_visibility_service.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

Add the show the linked_clone button in the provisioning dialog so the
user can specify if they want the clone to be linked(dependant) or not
(clone/independent)
requires: https://github.com/ManageIQ/manageiq/pull/18833
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1712934

Implement provisioning independent thin VM

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb

Fixes a sporadic test failure.
```
1) ManageIQ::Providers::Redhat::InfraManager::Refresh::Refresher will perform a full refresh on v4.1
Failure/Error: expect(v.ipaddresses).to eq(["10.35.18.141", "10.8.198.74", "2620:52:0:2310:21a:4aff:fe16:151", "fe80::292b:fe88:1efc:ed5a", "2620:52:0:8c4:77cd:1729:6e0f:d0fa", "fe80::21a:4aff:fe16:151"])
expected: ["10.35.18.141", "10.8.198.74", "2620:52:0:2310:21a:4aff:fe16:151", "fe80::292b:fe88:1efc:ed5a", "2620:52:0:8c4:77cd:1729:6e0f:d0fa", "fe80::21a:4aff:fe16:151"]
got: ["10.8.198.74", "10.35.18.141", "fe80::21a:4aff:fe16:151", "2620:52:0:8c4:77cd:1729:6e0f:d0fa", "fe80::292b:fe88:1efc:ed5a", "2620:52:0:2310:21a:4aff:fe16:151"]
(compared using ==)
```

Ipaddress order isn't guaranteed, ignore order

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

We did not implement skeletal provisioning for V4, the idea is to create
a new VM with new disks that have the same parameters as the original
ones but are not cloned.
The VM will have the blank template as its original template.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1716929

Add skeletal provisioning to V4

---

spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb

On Rails 5.1, this raises an ArgumentError.
```
1) ManageIQ::Providers::Redhat::InfraManager::Refresh::Refresher targeted refresh of a Vm should refresh new vm
Failure/Error: ems = ExtManagementSystem.find(ems_id)
ArgumentError:
You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`.
```

Pass id to AR::Base find, not AR::Base objs

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb

When cloning the template base the disk name on the vm name. So the disk
name will be "<vm_name>_Disk<number_of_disk>".
Implements: https://bugzilla.redhat.com/show_bug.cgi?id=1722073

[HAMMER] When cloning template base disk name on vm name

---

app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
spec/spec_helper.rb

There was an issue parsing the host ipaddress where if it were present
it would be overwritten by a DNS lookup, instead of doing the DNS lookup
if it were nil.  This led to a number of workarounds in the specs to
stub the Socket.getaddrinfo call which wouldn't be needed if it used the
ip addr from inventory properly.

Fix host ip address parsing

---

app/models/manageiq/providers/redhat/infra_manager.rb

The core checks if to use graph refresh by looking at the settings of
the specific provider, since we removed the option to disable it from
the settings we need to override that method.
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1731037

Fix potential bug for graph refresh

---

app/models/manageiq/providers/redhat/network_manager.rb
app/models/manageiq/providers/redhat/network_manager/refresh_parser.rb

We removed a bunch of old refresh parsers and this one needs to go, as well. 
Thank, Adam!

Remove old redhat refresh_parser

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

With new versions of the gem, pg has changed the error hierarchy.
The usage of PGError was causing problems in displaying the correct
exception in case of Postgres connection errors (wrong credentials,
db versions, ...)
Related to BZ bug: https://bugzilla.redhat.com/show_bug.cgi?id=1734770

PGError does not exist anymore

---

app/models/manageiq/providers/redhat/ansible_role_workflow.rb
spec/models/manageiq/providers/redhat/ansible_role_workflow_spec.rb

See https://github.com/ManageIQ/manageiq/pull/19140
Note that there was a bug here, as the method `post_playback` didn't exist in core and was thus never called (which means these temp dirs would leak)

Refactor runner usage due to core refactoring

---

app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb
app/models/manageiq/providers/redhat/inventory/collector.rb

Remove the usage of the ovirt gem and version 3 api from the SSA
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535782
Depends on: https://github.com/ManageIQ/manageiq-smartstate/pull/98

Remove v3 api form SSA

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

The current definition was being nil, when doing targeted
refresh, causing the DB lookup to fail.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1733513

Define host as proper lazy object

---

spec/models/manageiq/providers/redhat/ansible_role_workflow_spec.rb

The start method in the base class changed from calling pre_execute
directly to signaling it as a state transition in [1].
This caused this spec to fail because the expectations assumed the
pre_execute method had run.
[1] https://github.com/ManageIQ/manageiq/pull/19145

Fix AnsibleRoleWorkflow spec

---

spec/support/ovirt_sdk/connection_vcr.rb

Hitting the real revoke_access_token implementation was causing specs to hang on some OS (depending on the tcp timeout)

Mock revoke_access_token

---

spec/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml

Specs were red due to having numeric only passwords for OVN.
See: https://github.com/ManageIQ/manageiq-providers-openstack/pull/504
This changes the spec passwords to alphanumeric strings.

Fix specs - numeric only passwords

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb

When a vm goes in down status, the start_time info is missing and we can
avoid to overwrite with a nil the information we may already have.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1571895

Preserving Last Boot time

---

app/models/manageiq/providers/redhat/infra_manager/vm.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb

With the introduction of the Unified Conversion host Image (UCI), the conversion hosts will be virtual machines in either OpenStack or RHV. Currently, only hosts are allowed as conversion hosts in RHV. This PR is to adds the support for VMs.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1749775

Add supports_conversion_host to Vm

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Add a data-driven-forms params_for_create allowing dynamic API driven
UI form building and add the standard validate_credentials API.

Data-Driven create params and validate_credentials

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

Rename the validate_credentials method, decrypt the password if it is
encrypted, and ensure that the method returns a boolean not the raw
connection object.
https://github.com/ManageIQ/manageiq/issues/18818

Rename validate_credentials and other fixes

---

app/models/manageiq/providers/redhat/infra_manager.rb

Prevent people from using the constant directly by defining
`@params_for_create ||= {}.freeze`

Replace PARAMS_FOR_CREATE constant with @ ||=

---

spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb

Two specs were slow 'cause they were hitting low level libraries (OvirtSDK4) waiting for the timeout.
This PR introduces mock values and some lint fixes

Fix slow specs

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

rhevm_inventory and rhevm_service seems are not used anywhere in the
code
@miq-bot add_label cleanup

Remove two unused methods

---

app/models/manageiq/providers/redhat/network_manager/refresh_worker/runner.rb

The NetworkManager::RefreshWorker was removed in https://github.com/ManageIQ/manageiq-providers-openstack/pull/538 because the CloudManager::RefreshWorker does all the work for it.  This was inheriting from the NetworkManager::RefreshWorker::Runner but ther wasn't anything overridden from the BaseManager::RefreshWorker::Runner so we can just inherit directly from that.

The OpenStack Network RefreshWorker was removed

---

spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Depends on https://github.com/ManageIQ/manageiq/pull/19212
This breaks one current spec because the current code triggers `raise_event(:changed)` more often than it should. See https://github.com/ManageIQ/manageiq/pull/19212#issuecomment-526627820 for details.
With the PR in question, the mere act of creation would not trigger an auth changed event, only an update, so the MiqQueue numbers are lower.

Update specs to match behavior of change in core PR 19212 (auth user changed)

---

app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb

As a result of request from related BZ below we are excluding archived vms from being able to be reconfigurable. Similar change is being made in 1 more repository(https://github.com/ManageIQ/manageiq-providers-vmware/pull/467).
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1743533

Excluding archived vms from reconfigurable? method.

---

app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
app/models/manageiq/providers/redhat/infra_manager/vm/operations/relocation.rb
app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb

The ems_ref_obj property was added for VMware because the simple ems_ref
isn't enough to fully identify an object, everyone else simply set
ems_ref_obj = ems_ref which was pointless.
https://github.com/ManageIQ/manageiq/pull/19430

Remove ems_ref_obj

---

spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision/state_machine_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_via_iso/state_machine_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresh_recording_modifier_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_custom_attributes_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_host_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_template_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_huge_async_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_lans_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_target_host_4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

We are not using :use_ovirt_engine_sdk property setting 'cause the
ovirt SDK is the only one used right now.
No need to merge settings in specs nor to check with different values

No need to specify use_ovirt_engine_sdk anymore

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml

While reconfiguring disk attachments for a VM,
we need the virtio_scsi support flag to set the disk interface
accordingly, in case it's not specified.
Related to the PR
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/445

We need all VM details

---

app/models/manageiq/providers/redhat/infra_manager/metrics_capture.rb
spec/models/manageiq/providers/redhat/infra_manager/metrics_capture_spec.rb

Ovirt is an infra metrics capture class. subclassing the proper parent
part of ManageIQ/manageiq#19684
NOTE: this one is not open/shut like the others.
The hierarchy is a little odd. Especially since there is a NetworkManager with network capture
Wondering if this is good enough, or if we need to get into modules and the like

Subclass InfraManager metrics capture

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb

Add native viewer support to allow the download of the connection file.
In case of multiple available consoles the "spice" one is consider the
preferred.
In case of headless vm (with no consoles available) an exception is
raised.
This is PR is a dependency for:
- https://github.com/ManageIQ/manageiq-ui-classic/pull/6574
- https://github.com/ManageIQ/manageiq/pull/19675
Related to BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1451594

Native viewer support

---

tools/handle_rhv_storage_duplication.rb

We changed the way we set 'location' for block storages.
That will cause duplication of those storages during upgrade.
This script is meant to copy over the tags from the old storages and delete them.
See: ManageIQ/manageiq-providers-ovirt#387
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1697467

Script to remove storage duplication after upgrade

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

If a NIC doesn't have a vnic_profile looking up if it is an
external_network or not raises a NoMethodError trying to call
external_networks on a nil.
Fixes https://github.com/ManageIQ/manageiq-providers-ovirt/issues/456

Fix for NICs that don't have a vnic_profile

---

app/models/manageiq/providers/redhat/infra_manager.rb

Simple refactor to avoid a new instantiation using the factory method
@miq-bot add_label refactoring

Avoid a new OvirtServices instantiation

---

app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb

Html5 is not officially supported anymore in RHV.
We can disable it by default using a property in the settings file.
In this way the feature can be enabled at user own risk.
Related to BZ
https://bugzilla.redhat.com/show_bug.cgi?id=1668771

Html5 console disabled by default

---

config/settings.yml

Without ems_metrics_collector_worker_redhat section the server is unable to
start
See PR:
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/464

Ems metrics collector section should remain

---

app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb

'OvirtSDK4::Event's were stored in the full_data as object since the
beginnig. This was causing problems in the dequeue process

OvirtSDK4 objects conversion to Hash

---

app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb

We need to require the manageiq-smartstate gem in the scanning class to
prevent MiqServer#scan_metadata from the following error:
`uninitialized constant ManageIQ::Smartstate`

Require manageiq-smartstate in VmOrTemplate::Scanning

---

app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
app/models/manageiq/providers/redhat/infra_manager/provision_workflow/dialog_field_validation.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow/dialog_field_validation_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

We will now save the disk format as part of the refresh.
Will now allow the user to select disk_format
Will validate disk configuration.
Depends on: https://github.com/ManageIQ/manageiq-schema/pull/459
Depends on: https://github.com/ManageIQ/manageiq/pull/19849
Related to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6692
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1726590

Allow user to set format and sparsity during provisioning and validate config

---

spec/models/manageiq/providers/redhat/infra_manager/refresher/refresh_recording_modifier_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_template_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_vm_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_huge_async_spec.rb

Currently if you run the specs locally you will see the following warnings:
```
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_vm_spec.rb:16: warning: already initialized constant COUNTED_MODELS
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_template_spec.rb:11: warning: previous definition of COUNTED_MODELS was here
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_huge_async_spec.rb:15: warning: already initialized constant ORIG_YML_PATH
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresh_recording_modifier_spec.rb:12: warning: previous definition of ORIG_YML_PATH was here
```
~~This PR stubs out the constants properly, with the bonus that these warnings go away.~~
Edit: …

Fix constant redefinition warnings in specs

---

app/models/manageiq/providers/redhat/infra_manager/datacenter.rb
app/models/manageiq/providers/redhat/infra_manager/external_distributed_virtual_switch.rb
app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_multi_datacenter_network_spec.rb
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_multi_datacenter_network_recording.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_multi_external_network_ovn_provider.yml

In ovirt external networks with same name can be defined in the same ems but
not in the same datacenter.
We need a way to let external_distributed_virtual_switches belong to the
owning datacenter
Related to:
- https://bugzilla.redhat.com/show_bug.cgi?id=1751151
- https://github.com/ManageIQ/manageiq-providers-ovirt/pull/477
- https://github.com/ManageIQ/manageiq-providers-ovirt/pull/478

External networks belong to datacenter

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
app/models/manageiq/providers/redhat/infra_manager/vm.rb
app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
spec/factories/datacenter.rb
spec/factories/switch.rb
spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/v4_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb

Vm reconfiguration extended to NICs, allowing
user to add, remove and edit VM network interfaces
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/480
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1751151

Add network reconfiguration

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb

The external vlans must be retrieved from the cluster's parent
datacenter

Provision workflow fix

---

app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
spec/factories/datacenter.rb
spec/factories/switch.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb

Returns a list of available Vm vlans including the external ones
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/477
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/480
Related to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6710
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1751151

Available vlans for network reconfigure

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb

While reconfiguring disk attachments for a VM,
we need the virtio_scsi support flag to set the disk interface
accordingly, in case it's not specified.
Backport of https://github.com/ManageIQ/manageiq-providers-ovirt/pull/451
(cherry picked from commit ad5336cb7c4dfcfab5db17c951a4ceff92004d4e)
Related to BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1803775

[IVANCHUK] We need all VM details

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb

Fix issue when disk_add :interface option from VmReconfigure request was not passed to DiskAttachmentBuilder
virtio_scsi is default interface option in oVirt/RHV UI, so make it default in ManageIQ as well.
(cherry picked from commit d8d3bce735385e4c81e575ea7ad76e890395a844)
Backport of https://github.com/ManageIQ/manageiq-providers-ovirt/pull/445
Related to BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1803775
Depends on:
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/472

[IVANCHUK] Enable to set virtio_scsi disk attachment interface

---

app/models/manageiq/providers/redhat/inventory/parser/network_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/definitions/network_collections.rb
app/models/manageiq/providers/redhat/inventory/persister/network_manager.rb
app/models/manageiq/providers/redhat/network_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_ports_spec.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/response_yamls/network_ports_external_network_providers.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_ports_ovn_provider.yml
spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_ports_recording.yml

After network manager refresh, in case of an external_network connected
to a vm, the network_port.device should be the related vm guest_device
Related to:
https://github.com/ManageIQ/manageiq-providers-ovirt/issues/488

Fix relation between guest_device and network_port

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

This PR adds cpu affinity information for vms, aka cpu pinning, as a comma separated list of virtual cpu's that are pinned to a cpu set.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1846623

Add cpu_affinity for vms

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

Followup PR for https://github.com/ManageIQ/manageiq-providers-ovirt/pull/502, customer requested both virtual and physical cpu information be included.
Result will still be a comma separated string, e.g. `"0#3,1#2"` to keep it at least somewhat consistent with the current vmware provider format (the other provider where this is set). In the future this format may be changed, but for now this is it.

Update cpu affinity to include both virtual and host cpu

---

app/models/manageiq/providers/redhat/infra_manager/event_catcher/runner.rb

Without setting the monitor_running concurrent event the main event_catcher worker thread doesn't ever leave the do_before_work_loop which means it can't be shutdown cleanly until the first event is raised.
Related to: https://github.com/ManageIQ/manageiq-providers-amazon/pull/633

Set the monitor_running event to unblock the main thread

---

spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb

In core the use of MiqHashStruct was replaced with OpenStruct in miq_provision_virt_workflow so we need to change the expectations here to match.
Test failures: https://travis-ci.com/github/ManageIQ/manageiq-providers-ovirt/jobs/364034924#L2046-L2060
Introduced by: https://github.com/ManageIQ/manageiq/pull/20374

MiqHashStruct was replaced with OpenStruct in provisioning

---

app/models/manageiq/providers/redhat/infra_manager.rb
app/models/manageiq/providers/redhat/infra_manager/event_target_parser.rb
spec/models/manageiq/providers/redhat/infra_manager/event_target_parser_spec.rb

Targeted refresh for graph refresh uses an event_target_parser to build up a set of refresh targets from an ems_event.
https://github.com/ManageIQ/manageiq/issues/19999

Add an event_target_parser for graph targeted refresh

---

app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
config/settings.yml
spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb

Html5 is not officially supported anymore in RHV. We can disable it by default using a property in the settings file.
In this way the feature can be enabled at user own risk.
(cherry picked from commit e4158a0abf53ca7ae9028c36943825299a69b20a)
We need this change in ivanchuk for https://bugzilla.redhat.com/show_bug.cgi?id=1862600 so that the html5 console button is properly disabled in UI for RHV virtual machines.
I'm creating a separate backport PR, since a plain cherry-pick won't work here (the commit depends on another commits from native console work, which we still do not have in ivanchuk).

[IVANCHUK] html5 console will be disabled by default

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb

Apparently RHEL8 uses "qemu-guest-agent" as the name for guest tools instead of "ovirt-guest-agent", so this PR updates the code to look for both.
Followup to https://github.com/ManageIQ/manageiq-providers-ovirt/pull/505
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1846624

Look for qemu-guest-agent for tools status as well

---

app/models/manageiq/providers/redhat/infra_manager.rb

This has been also renamed in the DDFv2, strange, but the `text-field` stayed :confused:
cc @jerryk55

Rename textarea-field to textarea in the DDF provider form

---

app/models/manageiq/providers/redhat/infra_manager.rb

The tenant_id is usually set by the TenancyMixin based on the current user but the Ovirt NetworkManager is created during refresh so it doesn't match the InfraManager#tenant_id

Sync the tenant_id when creating a NetworkManager

---

app/models/manageiq/providers/redhat/infra_manager.rb

When you try to add a provider without filling out the `Metrics` and `RSA Key Pair` information, the `Save` button is greyed out. This is because all three `validate-provider-credentials` components are required by default. I made [some changes in the UI](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347) to have the [opposite default behavior and exposed a new attribute if we want to have it explicitly required. These two changes in combination should make only the `Default` credentials to be required.
@mzazrivec this should fix your issue

Make the default credentials required in the provider DDF

---

app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb

Add native viewer support to allow the download of the connection file. In case of multiple available consoles the "spice" one is consider the preferred and if spice is missing a message is logged. In case of headless vm (with no consoles available) an exception is raised.
This is ivanchuk-specific version of https://github.com/ManageIQ/manageiq-providers-ovirt/pull/452 (cherry picked from commit 6e127f2fc77ab98f4d9772070d3573d58c4d0406).
This PR needs to go in with https://github.com/ManageIQ/manageiq/pull/20640 and https://github.com/ManageIQ/manageiq-ui-classic/pull/7372
https://bugzilla.redhat.com/show_bug.cgi?id=1884211

[IVANCHUK] Native viewer support

---

spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_target_host_4_spec.rb

Hosts are supposed to be disconnected so that they can be reconnected in the future.  https://github.com/ManageIQ/manageiq/pull/20588 fixed this in core and this test should be updated to match
Fixes https://travis-ci.com/github/ManageIQ/manageiq-providers-ovirt/jobs/396112357#L2106-L2115

Hosts should be disconnected not deleted

---

app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb

Datacenters subclass EmsFolders and thus can't be two separate collections since they are the same table.
If you had for example two folders and a datacenter the persister.ems_folders collection would have the two folder inventory objects but the query manager.ems_folders would return three records including the datacenter.
This meant that the datacenter was being deleted by the ems_folders inventory collection, then the datacenters inventory collection was creating it.
This fix is to save all records for the table in the base collection and manually set the STI :type column (which was actually already being done).
Fixes https://github.com/ManageIQ/manageiq-providers-ovirt/issues/539

Fix for datacenters being recreated every refresh

---

app/models/manageiq/providers/redhat/infra_manager/vm.rb

The snapshot form in ui-classic has too complex provider-specific logic to decide what fields to show, so I'm making this simpler by moving the ovirt-specific form into this repo. The API will be able to [expose](https://github.com/ManageIQ/manageiq-api/pull/943) this schema if asked.
@miq-bot assign @agrare 
@miq-bot add_label enhancement

Declared DDF schema for creating snapshots

---

spec/models/manageiq/providers/redhat/infra_manager/vm_scan_spec.rb

It was found that RHV SSA was broken due to missing state transitions (see https://github.com/ManageIQ/manageiq/pull/20953 for more info).  We noticed that there wasn't a vm_scan_spec.rb like the other providers that implement SSA.
This doesn't cover everything but is basically a copy of the specs already in vmware and openstack repos updated for Ovirt.

Add a VmScan spec for Ovirt

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
spec/models/manageiq/providers/redhat/infra_manager_spec.rb

When adding the metrics endpoint information the verify credentials step only sends the options from the metrics endpoint tab.
The backend here was assuming that the default API options would always be present and the metrics options sometimes present.
This no longer matches how the UI sends verify credentials tasks now that the endpoints are split up into their own tabs.
Fixes https://github.com/ManageIQ/manageiq-providers-ovirt/issues/550

Fix metrics connection setup failure

---

manageiq-providers-ovirt.gemspec

Bump ovirt-engine-sdk to 4.4.0
(cherry picked from commit c9a538c2320801e3af2cedb68c7b6e4181d8a20d)

[JANSA] Bump ovirt-engine-sdk to 4.4.0

---

app/models/manageiq/providers/redhat/network_manager.rb

- `create_cloud_subnet_queue` method lives in the provider code but it is unnecessary and can be moved to core
Depends on:

Refactor create cloud subnet queue

---

app/models/manageiq/providers/redhat/network_manager.rb
app/models/manageiq/providers/redhat/network_manager/cloud_network.rb
app/models/manageiq/providers/redhat/network_manager/cloud_subnet.rb
app/models/manageiq/providers/redhat/network_manager/floating_ip.rb
app/models/manageiq/providers/redhat/network_manager/network_port.rb
app/models/manageiq/providers/redhat/network_manager/network_router.rb
app/models/manageiq/providers/redhat/network_manager/security_group.rb

There is code which expects that `ext_management_system.class::Model` exists, this clashes with the Redhat::NetworkManager subclasses which previously had classes but the openstack parser never set any records to use it.
On master we fixed the parser to set the correct `:type` and added a data-migration to fix existing records.  On morphy we couldn't run a data-migration so we just used the openstack types, this left us with the issue raised by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/569 which expects the classes to exist.
Creating aliases of these classes will let e.g. `CloudNetwork.class_by_ems` work and also return records (previously e.g. `ManageIQ::Providers::Ovirt::NetworkManager::CloudNetwork.all` would always return `[]` because `:type` was never set to that). …

[MORPHY] Create aliases for Redhat::NetworkManager subclasses

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

The `verify_credentials` was assuming the `verify_ssl` option was a boolean not an integer (also updated with the DDF changes), which meant that `verify_ssl ? VERIFY_PEER : VERIFY_NONE` was always returning VERIFY_PEER even if you wanted VERIFY_NONE.
Which didn't matter anyway because the exception handler would only raise if the exception string matched `/error.*sso/i` which it wouldn't if you had anything other than a username/password exception.  This meant you could point the RHV provider to literally anything and it would verify successfully :scream:

Fix default api verification always succeeding

---

app/models/manageiq/providers/redhat/infra_manager/api_integration.rb

The `check_connect_metrics` method returns true if the server is nil, the expectation being that no metrics endpoint info was passed by the user.
The metrics endpoint keys in the options have changed since the DDF changes, which resulted in the metrics_server _always_ being nil. This meant that no matter what info was passed in the form it would verity successfully.
Fixes https://github.com/ManageIQ/manageiq-providers-ovirt/issues/526

Fix metrics_endpoint info not passed to check_connect_metrics

---

manageiq-providers-ovirt.gemspec

This gem declaration doesn't belong in the core Gemfile
Required for:
* https://github.com/ManageIQ/manageiq/pull/21589

Move ovirt_metrics gem to ovirt gemspec

---

config/settings.yml

The `ExtManagementSystem#allow_targeted_refresh?` check looks to `Settings.ems_refresh.emstype.allow_targeted_refresh` to indicate if targeted refresh is supported.  For Ovirt this was returning `nil` and thus wasn't supported

Targeted refresh should default to enabled

---

manageiq-providers-ovirt.gemspec

We shouldn't require such a pessimistic version constraint here.

Allow minor relases of ovirt_metrics such as 3.1 for rails 6.1 support

---

app/models/manageiq/providers/redhat/infra_manager.rb

- add supports feature for iso_datastore
Depends on:
- https://github.com/ManageIQ/manageiq/pull/21726
- https://github.com/ManageIQ/manageiq-ui-classic/pull/8129

Add supports iso datastore

---

app/models/manageiq/providers/redhat/network_manager.rb

The NetworkManager for RHV is not supported for create by itself and can only be created as part of a RHV/Ovirt InfraManager.

The RHV NetworkManager is not standalone

---

app/models/manageiq/providers/redhat/network_manager/event_catcher.rb

Check if the events service is available before starting the OVN network event catcher and spinning restarting the event monitor.
```
INFO -- evm: MIQ(ManageIQ::Providers::Redhat::NetworkManager::EventCatcher::Runner#start_event_monitor) EMS [RHVdev1.rtp.raleigh.ibm.com] as [admin@internal] Validating Connection/Credentials
INFO -- evm: MIQ(ManageIQ::Providers::Redhat::NetworkManager#with_provider_connection) Connecting through ManageIQ::Providers::Redhat::NetworkManager: [rhvdev1 Network Manager]
INFO -- evm: MIQ(ManageIQ::Providers::Redhat::NetworkManager::EventCatcher::Runner#start_event_monitor) EMS [RHVdev1.rtp.raleigh.ibm.com] as [admin@internal] Starting Event Monitor Thread
WARN -- evm: MIQ(OpenstackNullEventMonitor#initialize) There was an problem establishing a connection to the …
```

Add all_valid_ems_in_zone to Network EventCatcher

---

app/models/manageiq/providers/redhat/infra_manager.rb

Fix issues with the metrics and keypair selector being posted to the API and not loading the proper value on edit.
Tested with https://github.com/ManageIQ/manageiq-ui-classic/pull/8312 reverted
Follow-up to: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/606
Dependents:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/8330

Fix metrics/keypair endpoint selector

---

app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb

The lazy_find_by method is no different from the lazy_find method now and will be removed in an upcoming inventory_refresh release

Replace lazy_find_by with simple lazy_find

---

app/models/manageiq/providers/ovirt/network_manager.rb

Add Ovirt OVN/NetworkManager support for creating cloud networks, subnets, and routers.
The OVN API is an Openstack Neutron compatible API so we can re-use the CRUD methods from the Openstack subclass.
Fixes https://github.com/ManageIQ/manageiq/issues/22109#issuecomment-1262262868

Add support for creating cloud network/subnets/routers

---

app/models/manageiq/providers/ovirt/infra_manager.rb
app/models/manageiq/providers/ovirt/infra_manager/iso_datastore.rb
app/models/manageiq/providers/ovirt/infra_manager/ovirt_services.rb
app/models/manageiq/providers/ovirt/inventory/collector/infra_manager.rb
app/models/manageiq/providers/ovirt/inventory/collector/target_collection.rb
app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb
app/models/manageiq/providers/ovirt/inventory/persister/infra_manager.rb
spec/factories/iso_datastore.rb
spec/models/manageiq/providers/ovirt/infra_manager/iso_datastore_spec.rb
spec/models/manageiq/providers/ovirt/infra_manager/ovirt_services/v4_spec.rb
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_lans_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_multi_datacenter_network_recording.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_network_ports_recording.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml

- since iso datastores are only used by oVirt/RHV, we can move its model from core and into the provider plugin
- iso datastores will be modelled as `Storage` objects with STI `:type => ManageIQ::Providers::Ovirt::InfraManager::IsoDatastore`
- `synchronize_advertised_images` functionality is now in a refresh and the images will be persisted
Depends on:
TODO:
Ref:
- https://github.com/ManageIQ/manageiq/issues/19440
@miq-bot add_label enhancement

Subclass IsoDatastore and transfer from core

---

app/models/manageiq/providers/ovirt/infra_manager/provision/cloning.rb

Fix RHV provisioning when calling `#find_destination_in_vmdb` due to looking for the wrong class name.

Fix RHV `#find_destination_in_vmdb` looking for the wrong type

---

app/models/manageiq/providers/ovirt/infra_manager/api_integration.rb
spec/models/manageiq/providers/ovirt/infra_manager_spec.rb

The verify_credentials method is looking for "ca_certs" in the default_endpoint hash but the key is "certificate_authority".
This means even if the user passes in a valid CA cert the verify call will fail because ca_certs will be `nil`
```
server, port, verify_ssl, ca_certs = default_endpoint&.values_at(
"hostname", "port", "verify_ssl", "ca_certs"
)
(byebug) ca_certs
nil
(byebug) default_endpoint.keys
["hostname", "verify_ssl", "certificate_authority", "port"]
```

Fix passing custom CA cert via DDF params

---

app/models/manageiq/providers/ovirt/infra_manager/host.rb

part of: https://github.com/ManageIQ/manageiq/pull/22336
The default verify_credentials used to be ws, but is now ssh. This code wants the new default behavior.
Deleting this copy/paste code

Use default host_verify_credentials

---

app/models/manageiq/providers/ovirt/infra_manager/vm/reconfigure.rb
spec/models/manageiq/providers/ovirt/infra_manager/vm/reconfigure_spec.rb

Ovirt VMs have no host assigned when they are not running.  This causes an exception to be raised when trying to reconfigure a VM that isn't running because we are using the host for the list of available lans.

Fix VM Reconfigure for stopped VMs

---

app/models/manageiq/providers/ovirt/infra_manager/vm/remote_console.rb

Related to: https://github.com/ManageIQ/manageiq-ui-service/pull/1839
Adds the `:proto` object to the API response in order to match other remote console responses and match existing service ui code/design.

Add Missing Protocol to Native Console API Response

---

app/models/manageiq/providers/ovirt/infra_manager/host.rb

We need an 'Enabled / Disabled field' to have the correct behavior for required parameters within the form. A continuation of https://github.com/ManageIQ/manageiq-providers-ovirt/pull/636
@miq-bot add-reviewer @Fryguy
@miq-bot add-reviewer @agrare
@miq-bot add-reviewer @kbrock

Adding Enabled / Disabled field

---

lib/manageiq-providers-ovirt.rb
lib/manageiq/providers/ovirt.rb
spec/spec_helper.rb

Adopt convention already supported by bundler and required by zeitwerk so we don't need to tell zeitwerk to ignore this lib/gem-name.rb file.

Drop lib/gem-name.rb in favor of lib/gem/name.rb

---

spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_ovn_provider.yml

This is showing the same failures as the openstack-family of providers but for some reason the value is in "expires" not "expires_at" so I can't pull in the VcrHelper to automate this.
For now just fixing this manually, we aren't able to re-record these easily yet anyway due to the OvirtSDK VcrConnection stuff.
Related:
* https://github.com/ManageIQ/manageiq-providers-red_hat_virtualization/pull/30

Fix OVN refresher spec "expires" causing failures

---

app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared/scanning.rb

Checking if vm storage type is supported for smartstate analysis scans when checking if vm supports smartstate analysis

Check supported storage type for vm Smartstate analysis scan

---

app/models/manageiq/providers/ovirt/infra_manager.rb
app/models/manageiq/providers/ovirt/infra_manager/event_catcher.rb
app/models/manageiq/providers/ovirt/infra_manager/metrics_collector_worker.rb
app/models/manageiq/providers/ovirt/infra_manager/provision.rb
app/models/manageiq/providers/ovirt/infra_manager/provision/configuration.rb
app/models/manageiq/providers/ovirt/infra_manager/provision_via_iso.rb
app/models/manageiq/providers/ovirt/infra_manager/provision_via_pxe.rb
app/models/manageiq/providers/ovirt/infra_manager/provision_workflow.rb
app/models/manageiq/providers/ovirt/infra_manager/refresh_worker.rb
app/models/manageiq/providers/ovirt/infra_manager/scanning.rb
app/models/manageiq/providers/ovirt/infra_manager/template.rb
app/models/manageiq/providers/ovirt/infra_manager/vm.rb
app/models/manageiq/providers/ovirt/infra_manager/vm/operations.rb
app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared.rb
app/models/manageiq/providers/ovirt/inventory.rb
app/models/manageiq/providers/ovirt/inventory/collector.rb
app/models/manageiq/providers/ovirt/inventory/parser.rb
app/models/manageiq/providers/ovirt/inventory/persister.rb
app/models/manageiq/providers/ovirt/network_manager.rb
app/models/manageiq/providers/ovirt/network_manager/cloud_network.rb
app/models/manageiq/providers/ovirt/network_manager/refresh_worker.rb

Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854

Drop require_nested and include_concern

---

app/models/manageiq/providers/ovirt/infra_manager.rb
app/models/manageiq/providers/ovirt/infra_manager/host.rb
app/models/manageiq/providers/ovirt/infra_manager/template.rb
app/models/manageiq/providers/ovirt/infra_manager/vm.rb
app/models/manageiq/providers/ovirt/infra_manager/vm/operations.rb
app/models/manageiq/providers/ovirt/infra_manager/vm/operations/guest.rb
app/models/manageiq/providers/ovirt/infra_manager/vm/operations/snapshot.rb
app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared/scanning.rb

@agrare please take a look at this one. The patterns are different from the other providers
feels like a number of these could just delegate the reason to the failed supports check
---
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Deprecating `unsupported_reason_add`. Returning the string instead
Note, these are all the same:
```ruby
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports_feature2?
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports?(:feature2)
unsupported_reason(:feature2) unless supports?(:feature2)
unsupported_reason(:feature2)
```

drop use of unuspported_reason_add

---

app/models/manageiq/providers/ovirt/connection_manager.rb
app/models/manageiq/providers/ovirt/discovery.rb
app/models/manageiq/providers/ovirt/infra_manager/admin_ui.rb
app/models/manageiq/providers/ovirt/infra_manager/api_integration.rb
app/models/manageiq/providers/ovirt/infra_manager/event_parser.rb
app/models/manageiq/providers/ovirt/infra_manager/metrics_capture.rb
app/models/manageiq/providers/ovirt/infra_manager/ovirt_services.rb

Requiring both of these libraries loads 61 files and consumes 10+ MB.

Delay load the ovirt_metrics and ovirtsdk4 client libraries

---

app/models/manageiq/providers/ovirt/infra_manager/event_target_parser.rb

When we moved to kafka event payloads which commonly contained symbol keys were all being returned with string keys due to JSON being the intermediate format across kafka.  We decided to `deep_symbolize_keys` when processing the event payload https://github.com/ManageIQ/manageiq/blob/master/app/models/miq_event_handler/runner.rb#L3 but RHV/Ovirt actually used string keys in their event payloads.
In order to support both kafka and MiqQueue we need to deep_symbolize_keys here
Dependents:
* https://github.com/ManageIQ/manageiq-providers-red_hat_virtualization/pull/51
Fixes https://github.com/ManageIQ/manageiq-providers-ovirt/issues/670

Fix EventTargetParser looking for string keys

---

app/models/manageiq/providers/ovirt/infra_manager/host.rb

Part of https://github.com/ManageIQ/manageiq/pull/22898 (as a followup)
Introduced by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/659
You can not have a return in a block. It causes a LongJump error Besides, it tries to return from inside the calling block - not what we want.
Fixes a missed unsupported reason check

Remove return from supports block

---

app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared/scanning.rb
spec/models/manageiq/providers/ovirt/infra_manager/vm_spec.rb

Introduced by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/659 this causes a failure when checking if unsupported_reason is nil

Fix typo in Ovirt VM supports?(:smartstate_analysis)

---

manageiq-providers-ovirt.gemspec

Updating gem because it fixes some issues with ruby 3.3 building
Gem released Feb 1, 2024
I have no idea if I'm breaking anything here.
Just trying to make ruby 3.2 compile

Update ovirt-engine-sdk to 4.6

---

app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared/scanning.rb

Newlines can cause trouble with translations as well as presentation in the UI. This particular string doesn't actually need the newlines, so this commit changes it to just not have them.
Alternative to ManageIQ/manageiq#23213
@agrare Please review.  cc @jrafanie 
I think this will also require a change in the ui-classic repo, since this string actually appears in the test snapshots.  Think it will be easier to make the PR if we merge this first however.

Remove newlines from error message
